OP-TEE/optee_test

host/xtest/xtest_10000.c
=> ECC Sign and Verify tests, at crypto_ops level

host/xtest/xtest_10000.c
=> ECC-DH self test

ta/os_test/tb_conv.c
Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>
=> GP11 : TEE Arithmetical API fix/panic reason

scripts/patch_gp_testsuite.sh
Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>
=> Fix xtest with GP testsuite

host/xtest/xtest_4000.c, host/xtest/xtest_helpers.c, host/xtest/xtest_helpers.h
=> TEE_GenerateKey(ECDSA / ECDH) testing

host/xtest/Makefile, scripts/patch_gp_testsuite.sh
=> Fix GP test patch when using OP-TEE repo installation

ta/os_test/testframework.c
=> mpa: allocator for temporary variables

host/xtest/xtest_4000.c
=> Test des3_cbc_mac in case of 112bits key

host/xtest/xtest_4000.c
This is to validate https://github.com/OP-TEE/optee_os/pull/420.
=> Test 4001: check that TEE_DigestDoFinal() resets the state

ta/os_test/include/testframework.h, ta/os_test/tb_gcd.c, ta/os_test/tb_prime.c
=> libmpa: remove DEBUG flag

host/xtest/xtest_6000.c
Signed-off-by: Aijun Sun <aijun.sun@linaro.org>
=> xtest_6000: initialize struct with TEEC_OPERATION_INITIALIZER

host/xtest/xtest_6000.c
- test extending file size
- test file hole
Signed-off-by: James Kung <james.kung@linaro.org>
Tested-by: James Kung <james.kung@linaro.org> (QEMU, MT8173 EVB)
=> Adding tee object test cases

Makefile
=> Fix openssl copy in case of 32bits distro

README.md
=> Fix wrong description of CFG_ARM32

Notice.md
`Signed-off-by: Joakim Bech <joakim.bech@linaro.org>`
=> Changing from old STM CLA to the new DCO

Makefile
=> Fix clean in case TA_DEV_KIT_DIR is wrongly defined

host/xtest/xtest_1000.c
Need https://github.com/OP-TEE/optee_os/pull/514 to be merge for all tests to pass.
=> Negative tests

ta/crypt/include/user_ta_header_defines.h
=> Make crypt ta multi-instance

ta/concurrent/atomic_a64.S, ta/concurrent/sub.mk, ta/crypt/cryp_taf.c, ta/os_test/os_test.c, ta/os_test/tb_conv.c, ta/storage/storage.c
64-bit fixes for TAs to work and compile for Aarch64.
=> ta: 64-bit fixes

host/xtest/xtest_20000.c
- obj_corrupt function support return TEEC_Result error code
- add error messages in obj_corrupt function
- support corrupt multiple bytes
- initial filename array variables to all zeros
Signed-off-by: James Kung <james.kung@linaro.org>
=> storage corrupt test refactoring

host/xtest/xtest_1000.c
xtest 1013 tests the concurrent TA feature. It lauches several threads
in parallel. Hence, the running behavior is quite sensible, and an
issue in concurrent TA could be raised or not depending on the
runtime.
Running the tests several times allow to run the test in slightly
different configuration, and has a higher probability to raise
potential issues.
=> Run xtest 1013 test 50 times

Android.mk
=> Android.mk: add missing tests (fixes build errors)

ta/os_test/sub.mk
=> os_test: define CFG_TA_FLOAT_SUPPORT in sub.mk

ta/os_test/include/user_ta_header_defines.h, ta/os_test/os_test.c
This new test is failing when https://github.com/OP-TEE/optee_os/pull/651 is not applied
=> Check long properties

ta/os_test/os_test.c
=> os_test: add property name in case of errors

ta/os_test/os_test.c
=> Fix compilation issue on fvp

ta/os_test/os_test.c
=> Fix compiling issue when CFG_TEE_TA_LOG_LEVEL=0

host/xtest/xtest_main.c
Depends on https://github.com/OP-TEE/optee_client/pull/47
=> Set default tee device name to NULL

ta/os_test/os_test.c
Depends on https://github.com/OP-TEE/optee_os/pull/753
=> os_test: add case for setjmp/longjmp

host/xtest/xtest_1000.c
Presuming that the tee-supplicant is configured to support loading TAs
from an alternate path, use this alternate path to write test TAs,
instead of trying to rename and overwrite the existing TA images.
This gives several benefits:
- The tests no longer assume that the TA directory is writable.  This
allows this test to pass on platforms where it is not.
- There is no longer a race with pressing Ctrl-C at an inopportune
time will leave a corrupted TA file in place instead of the correct
one.
This change affects test 1008.4 and 1008.5, "Load fake uuid TA", and
"Load corrupt TA".
Signed-off-by: David Brown <david.brown@linaro.org>
=> Avoid writing to the TA directory

host/xtest/xtest_1000.c, host/xtest/xtest_20000.c
Client library crashes if we try to work with unitialized session.
This patch adds checks on values returned by TEE_OpenSession() to
avoid segfaults.
Signed-off-by: Volodymyr Babchuk <vlad.babchuk@gmail.com>
=> Fixed crashes and minor refactoring.

host/xtest/xtest_20000.c
Update of REE FS format, need to be merged in sync with optee_os pull request https://github.com/OP-TEE/optee_os/pull/1151
Please ignore the commit "Bugfix case 5006" as that's part of another pull request.
=> Secure storage REE FS single file

host/xtest/xtest_10000.c
=> xtest 10001: run lenghty PBKDF2 test only if level >= 15

host/xtest/xtest_20000.c, host/xtest/xtest_6000.c
Needed by https://github.com/OP-TEE/optee_os/pull/1360
=> Update 20xxx test for hash tree

host/xtest/sdp_basic.c
Build issue found since the test is merged.
It's strange that I did not faced it before...
=> xtest: fix cast issue in sdp_basic.c

host/xtest/regression_6000.c, host/xtest/regression_9000.c, host/xtest/xtest_helpers.c, host/xtest/xtest_helpers.h
Needs https://github.com/OP-TEE/optee_os/pull/1481 for tests to pass
=> Sync with secure storage updates

host/xtest/regression_6000.c
=> Remove SQL-FS

ta/os_test/include/os_test.h, ta/os_test/include/ta_os_test.h
=> ta/os_test: remove unused code

host/xtest/aes_perf.c, ta/aes_perf/include/ta_aes_perf.h, ta/aes_perf/ta_aes_perf.c
This PR is aiming to be merged after the 2.6 release we're currently testing for.
=> Adds AES-GCM performance test in aes-perf

host/xtest/regression_6000.c
Regression xtest 6012 already tests creation and recreation of a persistent object. This change adds a test in 6012 to re-create the existing object without setting the overwrite attribute. Creation should fail but the object should not be altered and former open should succeed.
=> xtest storage: add a test case of creation of already existing object

host/xtest/regression_6000.c
The TA's storage should be independent of each other. What ever
TA #2 do should not affect TA #1's stroage.
Signed-off-by: Jianhui Li <airbak.li@hisilicon.com>
=> xtest storage: add case 6019 for storage independence

host/xtest/regression_1000.c
Adds regression case 1003 for read/write mutex testing.
Depends on https://github.com/OP-TEE/optee_os/pull/1942
=> regression: add case 1003 for mutex

host/xtest/regression_4000.c
AES XTS tests were kept separate from the other cipher tests for
historical reasons. Merge them together.
=> regression: 4003: merge *4003_xts() and *4003_no_xts()

ta/storage/storage.c
According to the GP spec V1.1, the object_id in create/open/rename
functions is not allowed to reside in the shared memory. This change
insures the test TAs use local buffers to store the target file ID.
Suggested-by: Zeng Tao <prime.zeng@hisilicon.com>
Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (Qemu, GP)
Note: there is no test checking that using object_id from SHM is forbidden. I will look at that.
=> xtest storage: can't use object_id from shared memory

ta/os_test/tb_addsub.c, ta/os_test/tb_mul.c, ta/os_test/testframework.c
Needed to compile with https://github.com/OP-TEE/optee_os/pull/2237
=> Remove mempool dependency

host/xtest/regression_1000.c, ta/os_test/Android.mk, ta/os_test_lib/Android.mk, ta/os_test_lib/include/os_test_lib.h
depends on https://github.com/OP-TEE/optee_os/pull/2380
@liuyq please ack!
=> ta: os_test_lib: add aosp support

host/xtest/regression_4000.c
Test case for issue https://github.com/OP-TEE/optee_os/issues/2355.
=> regression: 4003: add AES CBC test

host/xtest/regression_6000.c
Adds a test case for issue https://github.com/OP-TEE/optee_os/issues/2707.
=> regression: 6010: add rename conflict case (with close)

host/xtest/aes_perf.c, host/xtest/benchmark_2000.c, host/xtest/crypto_common.h, ta/aes_perf/ta_aes_perf.c
Suggested-by: Tetsuya Yoshizaki <yoshizaki.tetsuya@socionext.com>
=> xtest --aes-perf: add -u option to process buffer in several steps

host/xtest/regression_4000.c
The .in_incr field of struct xtest_mac_case is currently used for
a single step, that is, update() is called to process in_incr byte,
then the rest of the input buffer is passed to final().
This commit adds a macro which allows to run the CBC MAC update()
several times in chunks of in_incr bytes, then the remaining bytes
in the input buffer (<= in_incr) are passed to final(). One entry is
added to the mac_cases[] array.
=> regression: 4002: run one CBC MAC test in multiple increments

host/xtest/Makefile, host/xtest/benchmark_1000.c, host/xtest/regression_4100.c, host/xtest/sock_server.c, ta/crypt/arith_taf.c
These patches fix compilation against the musl C library.
=> Musl fixes

ta/os_test/os_test.c
Fixing two issues that make regression 1010 fail with Clang (tested on HiKey960).
=> Clang support

host/xtest/regression_4000.c, host/xtest/xtest_helpers.c, host/xtest/xtest_helpers.h, ta/crypt/cryp_taf.c, ta/crypt/include/cryp_taf.h, ta/crypt/include/ta_crypt.h, ta/crypt/ta_entry.c
Needs ~~https://github.com/OP-TEE/optee_os/pull/3545~~ Edit: https://github.com/OP-TEE/optee_os/pull/3560 was merged instead.
=> Detect SM2/SM3/SM4 support at run time

host/xtest/regression_1000.c
Replaces the compile time configuration based on CFG_SECSTOR_TA_MGMT_PTA
with a runtime test if PTA_SECSTOR_TA_MGMT_UUID is available.
Skips the "Load corrupt TA" substests if PTA_SECSTOR_TA_MGMT_UUID isn't
available.
=> regression_1008: skip subtests if PTA is unavailable

README.md
Signed-off-by: Markus S. Wamser <markus.wamser@mixed-mode.de>
=> Fix link to readthedocs.io

host/xtest/pkcs11_1000.c
=> pkcs11: test mechanism info

host/xtest/pkcs11_1000.c
Add test of C_OpenSession(), C_GetSessionInfo(), C_CloseSession() and
C_CloseAllSessions() from PKCS11 TA test token in pkcs11 regression
test 1002.
Test token over which test is made is the last slot found if the slot
list reported by the Cryptoki library. Helper function
init_lib_and_find_token_slot() takes care of Cryptoki pre-session setup.
=> pkcs11 1002: test session API functions

host/xtest/sdp_basic.c
=> regression 1014: fix bad memref test

host/xtest/regression_1000.c
Add sub test in regression test 1025 for invocation of a PTA with
a NULL memory reference.
=> regression 1025: test null memref on pta invocation

host/xtest/adbg/src/adbg_run.c, host/xtest/xtest_main.c
This P-R is based on https://github.com/OP-TEE/optee_test/pull/192.
Introduces **~~wildcards and~~** test exclusions in xtest command line.
=> xtest: exclude tests with -x option

host/xtest/regression_1000.c
=> xtest: inline description of test dependencies

host/xtest/pkcs11_1000.c
Adds 1005, 1006 and 1007 testing symmetric ciphers via
- C_EncryptInit()
- C_Encrypt()
- C_EncryptUpdate()
- C_EncryptFinal()
- C_DecryptInit()
- C_Decrypt()
- C_DecryptUpdate()
- C_DecryptFinal()
Co-developed-by: Etienne Carriere <etienne.carriere@linaro.org>
=> xtest: pkcs11: add symmetric cipher tests

Android.mk, host/xtest/Makefile
=> Fix compilation of regression_7000.c + include xml/

ta/os_test/os_test.c, ta/os_test/sub.mk, ta/os_test/ta_entry.c, ta/os_test_lib/include/os_test_lib.h, ta/os_test_lib/os_test_lib.c, ta/os_test_lib/sub.mk
Addressing https://github.com/OP-TEE/optee_test/issues/458.
=> Optional C++ and TLS tests

.gitignore
tags and TAGS are files created by ctags, a source code navigation tool.
Signed-off-by: Elvira Khabirova <e.khabirova@omprussia.ru>
=> .gitignore: add tags and TAGS

host/xtest/pkcs11_1000.c
Add 1010 for C_GenerateKey() with following mechanisms
supported:
PKCS11_CKM_GENERIC_SECRET_KEY_GEN
PKCS11_CKM_AES_KEY_GEN
=> xtest: pkcs11: add key generation tests

host/xtest/pkcs11_1000.c
Add 1011 for -
C_FindObjectsInit()
C_FindObjects()
C_FindObjectsFinal()
=> PKCS11: Test Cases for Object APIs - Finding Objects

host/xtest/pkcs11_1000.c
Add testing to cover cases of non-even addresses and larger return
buffers.
=> xtest: pkcs11: add serialization tests

host/xtest/pkcs11_1000.c
Access of session/token objects depends on the type of session.
Refer TABLE 3: ACCESS TO DIFFERENT TYPES OBJECTS BY DIFFERENT
TYPES OF SESSIONS in [1]
[1] PKCS #11 Cryptographic Token Interface Base
Specification Version 2.40 Plus Errata 01
=> ta: pkcs11 : Add test case to check access of objects

host/xtest/pkcs11_1000.c
Add test case 1014 for C_SetAttributeValue() and C_CopyObject()
=> xtest: pkcs11:  Add test for C_SetAttributeValue()

host/xtest/pkcs11_1000.c
Add test case to test calling for C_SeedRandom() and C_GenerateRandom().
=> xtest: pkcs11: Add tests for random number generation

host/xtest/pkcs11_1000.c
This PR is dependent on 
optee_os - https://github.com/OP-TEE/optee_os/pull/4397
https://github.com/OP-TEE/optee_os/pull/4390
optee_client - https://github.com/OP-TEE/optee_client/pull/257
=> Add test case for C_DeriveKey()

host/xtest/pkcs11_1000.c
Add test cases to test calling of:
- C_DigestInit
- C_Digest
- C_DigestUpdate
- C_DigestKey
- C_DigestFinal
=> xtest: pkcs11: Add tests for digest operations

Android.mk, host/xtest/pkcs11_1000.c, ta/supp_plugin/Android.mk
Depends on https://github.com/OP-TEE/optee_client/pull/269
=> Add plugin support for AOSP build

host/xtest/pkcs11_1000.c
Adds tests to exercise P-256, P-384 and P521 curve functionality.
- Key pair generation
- Signing and verification (single op)
- Signing and verification (multi stage)
Goes with::
- https://github.com/OP-TEE/optee_os/pull/4453
- https://github.com/OP-TEE/optee_client/pull/261
Relates to:
- OP-TEE/optee_os#4283
=> xtest: pkcs11: Add elliptic curve tests

host/xtest/regression_1000.c
Regression test 1013 (concurrency) is split in two: first, a small TA
is used in sub-case 1013.1, then a larger one is loaded in 1013.2. The
first sub-case normally passes on all platforms, but the second one may
fail on memory constrained platforms or configurations. To address this
issue, a couple of compile-time checks have been introduced (on
CFG_PAGED_USER_TA and CFG_VIRTUALIZATION). There are two problems with
this approach:
1. It is testing for features rather than actual memory constraints,
which is fragile.
2. CFG_VIRTUALIZATION isn't even exported into the TA dev kit by the
OP-TEE OS build environment, so it may happen that its value is different
in optee_os and in optee_test. Moreover, virtualization should be
transparent to TAs.
This commit removes the compile-time tests and …
=> xtest 1013: ignore out of memory errors on large TA

host/xtest/regression_4000.c
TEE_MACComputeFinal() is tested in regression 4002 but not the similar
function TEE_MACCompareFinal(). Add the necessary code for that.
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
=> regression 4002: test TEE_MACCompareFinal()

host/xtest/regression_2000.c
Adds a case to test reception of a truncated datagram.
Depends on https://github.com/OP-TEE/optee_client/pull/289 and https://github.com/OP-TEE/optee_os/pull/4952
=> regression_2004: add case for truncated datagram reception

host/xtest/regression_2000.c
Fixes the invalid assumption that a UDP packet is delivered to its
destination instantly. Also error out early in case received buffer
sizes doesn't match what's expected.
=> regression 2004: fix invalid assumption

host/xtest/regression_4000.c
=> A fix and some cleanup

host/xtest/stats.c
OP-TEE supports a debug method to dump user TA's runtime context through stats PTA. The patch is to extend xtest to support it.
Tested-by: Weizhao Jiang <weizhaoj@amazon.com>
Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>
Signed-off-by: Weizhao Jiang <weizhaoj@amazon.com>
=> xtest: stats: Add loaded ta context dump

.github/workflows/ci.yml
Add a CI script to build and run xtest with QEMU on push and pull request.
=> Add GitHub CI script

host/xtest/xtest_uuid_helpers.c
Fix the following compilation error:
$ CROSS_COMPILE=... OPTEE_CLIENT_EXPORT=... TA_DEV_KIT_DIR=... \
WITH_OPENSSL=n make
/optee_test/host/xtest/xtest_uuid_helpers.c: In function ‘xtest_uuid_to_allocated_str’: /optee_test/host/xtest/xtest_uuid_helpers.c:91:13: error: implicit declaration of function ‘malloc’ [-Werror=implicit-function-declaration]
91 |         s = malloc(UUID_STR_LEN);
|             ^~~~~~
/optee_test/host/xtest/xtest_uuid_helpers.c:16:1: note: include ‘<stdlib.h>’ or provide a declaration of ‘malloc’
15 | #include "xtest_uuid_helpers.h"
+++ |+#include <stdlib.h>
16 |
/optee_test/host/xtest/xtest_uuid_helpers.c:91:13: error: incompatible implicit declaration of built-in function ‘malloc’ [-Werror=builtin-declaration-mismatch]
91 |         s = malloc(UUID_STR_LEN);
| …
=> xtest: fix compilation error with WITH_OPENSSL=n

ta/os_test/os_test.c
ta: os_test: fix print_properties() indentation
Fixes print_properties() indentation as per OP-TEE coding style.
Signed-off-by: Chang YuQing<08182924@cumt.edu.cn>
Reviewed-by: Etienne Carriere <etienne.carriere@foss.st.com>
=> ta: os_test: fix print_properties() indentation

host/xtest/pkcs11_1000.c
This test involves `PKCS11_CKA_CHECK_VALUE ` when enabled, as per the spec, the attribute can be either the legitimate value recomputed by the PKCS#11 token or a zero-sized value called a no-value for when client does not want the attribute to set in an object. This test invokes Cryptoki API functions `C_GenerateKey()`, `C_CreateObject()`, `C_CopyObject()`, `C_SetAttributeValue()`, `C_UnwrapKey()` and `C_DeriveKey()` to perform check value computation and this test query the value using `C_GetAttributeValue()`.
=> xtest: pkcs11_1000.c: Test support of object checksum value computation

host/xtest/regression_4000.c
Depending on the crypto engine used, the generated DH private value might be different from the expected key size.
This is true for the CAAM black key implementation where the private key is encapsulated in a blob format that contains additionnal data, resulting in a bigger buffer.
=> regression_4000: do not check DH private value key size

Android.mk, host/xtest/CMakeLists.txt, host/xtest/Makefile, host/xtest/symm_cipher_perf.c, ta/crypto_perf/include/ta_crypto_perf.h, ta/crypto_perf/ta_crypto_perf.c
Add perf test for SM4 algorithm
=> xtest: add SM4 perf test

scripts/aes_gcm_test.py
Add the license to BSD-2-Clause and NXP copyright to aes_gcm_test.py script.
=> regression 4005: scripts: update license and copyright

host/xtest/xtest_main.c
=> xtest: Fix typo from 'Unkown' to 'Unknown'

.github/issue_template.md, .github/pull_request_template.md
The readthedoc.io urls are broken, and this fixes broken links
=> github: update links in the pull_request and issue template

host/xtest/ffa_spmc_1000.c
Fix in ffa_spmc_1006 test for a minor issue I saw lately reviewing  already merged P-R #793
=> ffa_spmc: fix ffa_spmc_1006 unbalanced end subcase
