OP-TEE/optee_test

- host/xtest/xtest_4000.c
- ta/crypt/cryp_taf.c
ta_crypt_cmd_ae_init() passed some value parameters as output instead of
input.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU)
> bugfix test case 4005

- host/xtest/xtest_4000.c
Log:
xtest_4000.c: In function ‘xtest_tee_test_4009’:
xtest_4000.c:4271:16: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
for (i = 0; i < ARRAY_SIZE(derive_key_ecdh); i++) {
^
cc1: all warnings being treated as errors
Signed-off-by: Peng <van.freenix@gmail.com>
> xtest_4000 fix build errors

- ta/os_test/include/tb_asserts.h
- ta/os_test/include/testframework.h
- ta/os_test/tb_addsub.c
- ta/os_test/tb_div.c
- ta/os_test/tb_fmm.c
- ta/os_test/tb_modulus.c
- ta/os_test/tb_mul.c
- ta/os_test/tb_shift.c
- ta/os_test/testframework.c
Dropping the groupsize parameter for mpa_get_str().
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU)
need to be merged in sync with https://github.com/OP-TEE/optee_os/pull/409
> API change for mpa_get_str()

- ta/os_test/include/user_ta_header_defines.h
Increase size of os_test TA beyond 1 MB of code and data.
Tests that the fix for a large va space for TAs still works.
> ta os_test: increase size beyond 1 MB

- host/xtest/adbg/src/adbg_log.c
This makes debugging easier by keeping messages in sync with the ones
logged by OP-TEE (assuming OP-TEE also flushes its output
synchronously).
> Flush standard output each time a message is displayed

- .gitignore
- Makefile
- host/xtest/Makefile
xtest_7000.c contains a subset of the GP tests in TEE.xml (the 29-*
series). When GP tests are enabled, instead of patching xtest_7000.c
we can just generate a new file called xtest_7000_gp.c with all the
tests from TEE.xml. This avoids modifying a source file that is managed
by Git.
> GP tests: don't patch xtest_7000.c, create xtest_7000_gp.c instead

- host/xtest/xtest_helpers.h
If the struct TEEC_TempMemoryReference in TEE client API is changed
with union members added, the macro TEEC_OPERATION_INITIALIZER
need be changed also for union member initialization.
The alternative macro is defined in the TEE client API header file.
Signed-off-by: Aijun Sun <aijun.sun@linaro.org>
Tested-by: Aijun Sun <aijun.sun@linaro.org> (FVP and Qemu)
> Check if TEEC_OPERATION_INITIALIZER has been defined

- Android.mk
- host/xtest/xtest_20000.c
The correct fopen() mode string to open an existing file in read/write
mode and set the stream pointer at the beginning is 'r+'.
'rw+' is invalid and causes the file to be open read-only on Android.
> xtest_20000.c: Fix fopen() mode string

- .gitignore
- Android.mk
- host/xtest/xtest_1000.c
- Add Android.mk which can be used to build the client side (xtest
binary) using the Android NDK.
- xtest_1000.c: make the path to TA files configurable via a macro
Note: the additional GlobalPlatform tests (see CFG_GP_PACKAGE_PATH in
the regular Linux Makefile) are not supported.
> Android support

- Makefile
- host/xtest/Makefile
- ta/Makefile
Required to override cross compile variables with cross compile
variables set by yocto environment.
Also LDFLAGS should be empty to properly compile trusted application
with yocto.
Signed-off-by: Sumit Garg <b49020@freescale.com>
> Make cross compile variables configurable via the environment

- host/xtest/xtest_1000.c
Fixes out of secure memory problem with running this test case with LPAE.
The out of memory problem was introduced by
38a66f9 Make crypt ta multi-instance
Previously the crypt ta was signle-instance, multi-session allowing
several open sessions share the same context (and saving some memory).
When the crypt ta is instead multi-instance test case 1008 indirectly
loads two instances of crypt TA which is too here.
This patch skips the first session to crypt TA which was opened first in
the test case due to legacy reasons.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)
> xtest 1008: fix out of memory problem

- host/xtest/xtest_main.c
xtest without arguments tries to run a test suite regression, but the
suite isn't found as the rest of the code thinks the name is supposed to
be sanity. This patch fixes that.
> xtest: name of default test suite is regression

- ta/os_test/os_test.c
- ta/os_test/sub.mk
- ta/os_test/test_float_subj.c
- ta/os_test/test_float_subj.h
Adds basic test for floating point.
Depends on https://github.com/OP-TEE/optee_os/pull/584
> os_test: add basic tests for floating point

- ta/concurrent/atomic_a32.S
- ta/concurrent/atomic_a64.S
Sets type for assembly functions.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU)
> concurrent_ta: set type for assembly functions

- host/xtest/Makefile
Compilation of xtest requires linking to the precompiled library
libcrypto.a. Hence it needs to know in which mode (32bits / 64bits) xtest
is compiled.
Before this patch, it was believed that the compilation mode of the client
part is the same as the optee_os core part. This is not true and fixed
using optional environment variable COMPILE_NS_USER, which is defined
by default the same as the optee_os core compilation mode
> xtest client: compilation mode (32bits / 64bits) fix

- .gitignore
Tells Git to ignore any file or folder named like the GlobalPlatform
test suite package (TEE_Initial_Configuration-Test_Suite*), so that Git
won't complain about modified content when the test suite is extracted
in the main directory.
> .gitignore: add name of GlobalPlatform test suite package

- host/xtest/xtest_6000.c
- ta/storage/storage.c
Depends on https://github.com/OP-TEE/optee_os/pull/759
> xtest 6009: TEE_GetNextPersistentObject with objectInfo==NULL

- host/xtest/xtest_benchmark_1000.c
Resolve maybe-uninitialized compiler warning.
Moving patch from meta-los to upstream:
https://github.com/kuscsik/meta-los/blob/5c5a2e33bcda865ec581bc581eccf12f9fea1ada/recipes-security/optee/optee-test/0001-Silence-may-be-unset-CLang-warning.patch
Signed-off-by: Zoltan Kuscsik <zoltan.kuscsik@linaro.org>
> benchmark: initialize local var.

- host/xtest/xml/include/xml_internal_api.h
Allocation flags, in test 8051 to 8054, were TEEC_MEMREF_PARTIAL_INPUT,...
instead of TEEC_MEM_INPUT,...
> Fix shm allocation flags in 8051 to 8054

- ta/os_test/tb_gcd.c
Fixes a compilation warning/error when tests are build with NDEBUG
defined (make CPPFLAGS=-DNDEBUG) if OP-TEE pull request #910 [1] is
merged.
[1] https://github.com/OP-TEE/optee_os/pull/910
> Add __maybe_unused to variable used only in assert()

- ta/os_test/os_test.c
Cleans up undefined instruction test by using a separate
assembly implementation for the undefined instruction.
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU, FVP)
> os_test: cleanup undef instruction test

- Android.mk
- host/xtest/Makefile
- host/xtest/xtest_20000.c
- host/xtest/xtest_6000.c
- ta/storage/storage.c
Update xtest 6xxx to test the OP-TEE specific storage IDs
(TEE_STORAGE_PRIVATE_REE, TEE_STORAGE_PRIVATE_RPMB) in addition to the
default, GP-defined value: TEE_STORAGE_PRIVATE. Which values are
enabled is determined at compile time based on whether CFG_REE_FS and
CFG_RPMB_FS are 'y' or 'n' (these values are exported by optee_os and
may be overriden).
Among all the tests in the 6xxx series, 6009 and 6010 are not updated
(i.e., they test only TEE_STORAGE_PRIVATE) because they are GP tests.
xtest_20000.c is updated accordingly, due to the change in the
interface between xtest and the secure storage TA.
> xtest 6xxx: test multiple storage IDs as supported by OP-TEE

- Android.mk
- host/xtest/Makefile
Helps debugging (gdb, valgrind).
> Always build xtest with -g3

- host/xtest/xtest_6000.c
If OP-TEE was compiled with SQL FS support (CFG_SQL_FS=y), test the
specific storage ID.
> xtest 6xxx: add TEE_STORAGE_PRIVATE_SQL

- host/xtest/xtest_6000.c
Fix compiler warning introduced by commit 29d7c7a486e4 ("xtest: add
6016 to test concurency storage"):
/home/travis/optee_repo/optee_test/host/xtest/xtest_6000.c: In function 'xtest_tee_test_6016_loop':
/home/travis/optee_repo/optee_test/host/xtest/xtest_6000.c:1549:12: error: passing argument 1 of 'snprintf' from incompatible pointer type [-Werror=incompatible-pointer-types]
snprintf(&arg[n].file_name, sizeof(arg[n].file_name),
^
In file included from /home/travis/optee_repo/optee_test/host/xtest/xtest_6000.c:15:0:
/home/travis/build/jforissier/optee_os/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/include/stdio.h:386:12: note: expected 'char * restrict' but argument is of type 'uint8_t (*)[8] {aka unsigned char (*)[8]}'
extern int snprintf (char …
> xtest: fix compiler warning

- host/xtest/xtest_6000.c
Fixing parent commit. Sometimes two pairs of eyes are not even enough
to fix a single line of code ;O (and the fact that my local compiler is
not the same as the one used by Travis does not help).
/home/travis/optee_repo/optee_test/host/xtest/xtest_6000.c:1549:12: error: passing argument 1 of 'snprintf' from incompatible pointer type [-Werror=incompatible-pointer-types]
snprintf(&arg[n].file_name, sizeof(arg[n].file_name),
^
In file included from /home/travis/optee_repo/optee_test/host/xtest/xtest_6000.c:15:0:
/home/travis/build/OP-TEE/optee_os/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/arm-linux-gnueabihf/libc/usr/include/stdio.h:386:12: note: expected 'char * restrict' but argument is of type 'char (*)[8]'
extern int snprintf (char *__restrict __s, size_t __maxlen,
^ …
> xtest: fix compiler warning (redux)

- host/xtest/xtest_6000.c
Depends on https://github.com/OP-TEE/optee_os/pull/1047.
> Enable xtest 6016 (storage concurrency) for all backends

- host/xtest/xtest_6000.c
host/xtest/xtest_6000.c: In function ‘xtest_tee_test_6016_loop’:
host/xtest/xtest_6000.c:1629:4: error: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘size_t’ [-Werror=format=]
"file_%d", n);
^
host/xtest/xtest_6000.c:1629:4: error: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘size_t’ [-Werror=format=]
cc1: all warnings being treated as errors
> Fix 64-bit compile error in case xtest_6000.c

- README.md
What additional info it will be good to add about benchmarks?
FYI, I've used the term "modules" to describe aes-perf/sha-perf test tools, that are included into xtest. We can use them by running: 
$ xterm --sha-perf
If it's OK, I will also change "applets" to "modules" in the usage output for xtest utility
> Added info about available benchmarks within xtest tool

- Android.mk
TA_DEV_KIT_DIR must be set to non-empty value to
avoid the Android build scripts complaining about
includes pointing outside the Android source tree.
This change fixes the AOSP builds which include
optee_test in their source tree, but OPTEE is not
added to the PRODUCT_PACKAGES.
> Android.mk: set TA_DEV_KIT_DIR default value

- host/xtest/xml/include/xml_common_api.h
- host/xtest/xml/include/xml_crypto_api.h
- host/xtest/xml/include/xml_datastorage_api.h
- host/xtest/xml/include/xml_internal_api.h
- host/xtest/xml/include/xml_timearithm_api.h
Add additional labels so that cleanup order is correct
Change deallocation order
All test cases are successfully passed
> Fix for #117 xml_crypto_api.h contains multiple free of unallocated errors

- ta/os_test/include/os_test.h
- ta/os_test/include/ta_os_test.h
- ta/os_test/os_test.c
- ta/os_test/ta_entry.c
Related to [optee_os/pull#119](https://github.com/OP-TEE/optee_os/pull/1119).
TA private memory definition has changed. Memory reference received
as parameters by an TA when invoked are never "private TA memory",
they are at least shared with the client(s) in some way.
As a side effect, when a TA invokes a TA relaying a memref parameter,
the invoked TA sees memory as ANY_OWNER: it is non secure shared memory.
When a TA invoke a TA with its private memory (stack, heap, code/data)
as memref parameter, the invoked TA sees ANY_OWNER memory, mapped secure,
inside TEE reserved memory (TA RAM).
Since this change, xtest 1006 is broken.
Rename PRIVATE_PARAMS into PARAM_ACCESS tests.
Run TEE_CheckMemoryAccessRights() on several areas of the memory space.
Fix TA that see memref parameters as …
> update xtest on new "TA private memory definition"

- host/xtest/xtest_5000.c
Bugfixing case 5006, don't call TEEC_ReleaseSharedMemory on shared memory
that wasn't successfully allocated or registered.
Signed-off-by: Jens Wiklander jens.wiklander@linaro.org
> Bugfix case 5006

- host/xtest/xtest_1000.c
Make sure that all temporary test data is under
/data/tee, so we don't have to define multiple
SElinux policies.
Signed-off-by: Zoltan Kuscsik zoltan.kuscsik@linaro.org
> Update temporary data path for xtest on Android

- host/xtest/xtest_20000.c
Fix the compilation errors shown below by specifying correct printf
conversions.
optee_test/host/xtest/xtest_20000.c: In function 'obj_corrupt':
optee_test/host/xtest/xtest_20000.c:349:20: error: format '%d' expects argument of type 'int', but argument 3 has type 'size_t {aka long unsigned int}' [-Werror=format=]
fprintf(stderr, "fseek(%d): %s",
^
optee_test/host/xtest/xtest_20000.c:364:10: error: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'size_t {aka long unsigned int}' [-Werror=format=]
printf("o Byte offset: %u (0x%04X)\n", real_offset, real_offset);
^
optee_test/host/xtest/xtest_20000.c:364:10: error: format '%X' expects argument of type 'unsigned int', but argument 3 has type 'size_t {aka long unsigned int}' [-Werror=format=] …
> xtest_20000: Fix printf conversions

- host/xtest/xtest_1000.c
- ta/aes_perf/Android.mk
- ta/aes_perf/Makefile
- ta/concurrent/Android.mk
- ta/concurrent/Makefile
- ta/concurrent_large/Android.mk
- ta/concurrent_large/Makefile
- ta/create_fail_test/Android.mk
- ta/create_fail_test/Makefile
- ta/crypt/Android.mk
- ta/crypt/Makefile
- ta/os_test/Android.mk
- ta/os_test/Makefile
- ta/rpc_test/Android.mk
- ta/rpc_test/Makefile
- ta/sha_perf/Android.mk
- ta/sha_perf/Makefile
- ta/sims/Android.mk
- ta/sims/Makefile
- ta/storage/Android.mk
- ta/storage/Makefile
- ta/storage2/Android.mk
- ta/storage2/Makefile
- ta/storage_benchmark/Android.mk
- ta/storage_benchmark/Makefile
Prior to this patch although GlobalPlatform specifies that TAs and such
are identified with UUIDs, we don't format them quite right when turning
them into strings. Per https://www.ietf.org/rfc/rfc4122.txt, there
should be another hyphen after the first two bytes of clockSeqAndNode.
Unfortunately, fixing this breaks compatibility between how TAs are
built, and when the OS loads them.
With this patch UUID string are formated with the additional hyphen as
for instance: f81d4fae-7dec-11d0-a765-00a0c91e6bf6
Fixes: https://github.com/OP-TEE/optee_os/issues/857
Depends on https://github.com/OP-TEE/optee_os/pull/1227 and https://github.com/OP-TEE/optee_client/pull/71
> Format UUID strings correctly

- Makefile
Forgot to adjust the sed rule in parent commit. As a result, unwanted GP tests
would run.
Fixes: b6bea047b1d4 ("Update GP tests after simplification of test declarations")
> Update Makefile rule for filtering out GP tests

- host/xtest/xtest_10000.c
Resolves the same issue as #161, but keeping the variable.
> Fix issue with pbkdf2_4_dkm not defined

- host/xtest/Makefile
- host/xtest/rand_stream.c
initstate_r() and friends are glibc extensions which are not available
in all libc. This patch removes this dependency and implements its own
portable implementation.
> xtest: fix dependency to initstate_r() and friends

- host/xtest/aes_perf.c
- host/xtest/sha_perf.c
Show more statistics to help assess the test repeatability and compare
test runs:
- Print the coefficient of variation (cv = stddev/mean)
- When the -v option is given: also show the 2-sigma interval
> aes-perf, sha-perf: display more statistics

- host/xtest/xtest_6000.c
Reduces the number of blocks written to avoid out of memory errors on some
platforms.
> case 6018: reduce the number of blocks written

- host/xtest/xtest_6000.c
xtest 6010 is updated to test TEE_AllocatePersistentObjectEnumerator()
immediately followed by TEE_ResetPersistentObjectEnumerator().
> Add test case for allocate + reset persistent object enumerator

- ta/Makefile
The compile-time options of OP-TEE OS (CFG_*) are currently not
available from the main TA makefile. Fix this, since we already
have a need (the sdp_basic TA should automatically be selected
when OP-TEE supports the Secure Data Path).
> ta/Makefile: include host_include/conf.mk

- host/xtest/aes_perf.c
- host/xtest/sha_perf.c
- host/xtest/xtest_main.c
Fix usage info.
Fix timing traces (prefer plain ASCII traces 'us' than UTF-8 'µs').
Remove undefined VERSION info.
Remove few trailing spaces and empty lines.
Add few spaces for source code layout consistency.
> xtest: minor cleanups in aes/sha performance tests

- host/xtest/sdp_basic.c
- host/xtest/sdp_basic.h
- host/xtest/xtest_1000.c
- host/xtest/xtest_test.c
- host/xtest/xtest_test.h
xtest regression test #1014 is dedicated to secure data path.
It is enable only upon CFG_SECURE_DATA_PATH=y.
> xtest: add a SDP test in the non-regression suite

- package/testsuite/global_platform/api_1.0/GP_XSL_TEE_Initial_Configuration-Test_Suite_v1_0_0-2014-12-03-STM/TTAs/TTA_Arithmetical/code_files/sub.mk
- package/testsuite/global_platform/api_1.0/GP_XSL_TEE_Initial_Configuration-Test_Suite_v1_0_0-2014-12-03-STM/TTAs/TTA_ClientAPI/TTA_answerErrorTo_Invoke/code_files/sub.mk
- package/testsuite/global_platform/api_1.0/GP_XSL_TEE_Initial_Configuration-Test_Suite_v1_0_0-2014-12-03-STM/TTAs/TTA_ClientAPI/TTA_answerErrorTo_OpenSession/code_files/sub.mk
- package/testsuite/global_platform/api_1.0/GP_XSL_TEE_Initial_Configuration-Test_Suite_v1_0_0-2014-12-03-STM/TTAs/TTA_ClientAPI/TTA_answerSuccessTo_OpenSession_Invoke/code_files/sub.mk
- package/testsuite/global_platform/api_1.0/GP_XSL_TEE_Initial_Configuration-Test_Suite_v1_0_0-2014-12-03-STM/TTAs/TTA_ClientAPI/TTA_check_OpenSession_with_4_parameters/code_files/sub.mk
- package/testsuite/global_platform/api_1.0/GP_XSL_TEE_Initial_Configuration-Test_Suite_v1_0_0-2014-12-03-STM/TTAs/TTA_ClientAPI/TTA_testingClientAPI/code_files/sub.mk
- package/testsuite/global_platform/api_1.0/GP_XSL_TEE_Initial_Configuration-Test_Suite_v1_0_0-2014-12-03-STM/TTAs/TTA_Crypto/code_files/sub.mk
- package/testsuite/global_platform/api_1.0/GP_XSL_TEE_Initial_Configuration-Test_Suite_v1_0_0-2014-12-03-STM/TTAs/TTA_DS/code_files/sub.mk
- package/testsuite/global_platform/api_1.0/GP_XSL_TEE_Initial_Configuration-Test_Suite_v1_0_0-2014-12-03-STM/TTAs/TTA_TCF/TTA_TCF/code_files/sub.mk
- package/testsuite/global_platform/api_1.0/GP_XSL_TEE_Initial_Configuration-Test_Suite_v1_0_0-2014-12-03-STM/TTAs/TTA_TCF/TTA_TCF_ICA/code_files/sub.mk
- package/testsuite/global_platform/api_1.0/GP_XSL_TEE_Initial_Configuration-Test_Suite_v1_0_0-2014-12-03-STM/TTAs/TTA_TCF/TTA_TCF_ICA2/code_files/sub.mk
- package/testsuite/global_platform/api_1.0/GP_XSL_TEE_Initial_Configuration-Test_Suite_v1_0_0-2014-12-03-STM/TTAs/TTA_TCF/TTA_TCF_MultipleInstanceTA/code_files/sub.mk
- package/testsuite/global_platform/api_1.0/GP_XSL_TEE_Initial_Configuration-Test_Suite_v1_0_0-2014-12-03-STM/TTAs/TTA_TCF/TTA_TCF_SingleInstanceTA/code_files/sub.mk
- package/testsuite/global_platform/api_1.0/GP_XSL_TEE_Initial_Configuration-Test_Suite_v1_0_0-2014-12-03-STM/TTAs/TTA_Time/code_files/sub.mk
- ta/include/GP_defs.h
With [1], SLogTrace(), SLogError(), SLogWarning() and S_VAR_NOT_USED()
are not defined in tee_internal_api.h anymore. Define them locally.
[1] https://github.com/OP-TEE/optee_os/pull/1449
> GP: do not expect to find non-standard macros in tee_internal_api.h

- host/xtest/xtest_main.c
This is a minor change. Yet it prevents getting a "success" status when running `xtest 1001` (that does not complain when test fails, for good reasons) over a corrupted setup.
> xtest: fail straight if failing to open tee context

- host/xtest/xtest_main.c
Fixes: 69f914daa4dc ("xtest: fail straight if failing to open tee context")
> xtest: fix bug

- host/xtest/adbg/src/adbg_run.c
TAILQ_CONCAT() is currently unavailable in bionic so define it if
undefined.
> adbg_run.c: Define TAILQ_CONCAT() for aosp

- host/xtest/regression_6000.c
Reduces the number of blocks written when testing RPMB filesystem to
avoid occasional out of memory errors.
> regression 6018: reduce the number of blocks written

- host/xtest/sdp_basic.c
Clearly print "Test passed" or "Test failed" for each test, and do not
print "failed" when it is expected.
Fixes: https://github.com/OP-TEE/optee_test/issues/207
> --sdp-basic: fix misleading messages

- host/xtest/regression_5000.c
Fix for the Travis failures we're seing currently (for example https://travis-ci.org/OP-TEE/optee_os/builds/235179728#L4844) caused by the optee_client update: 9faeb1b6b023 ("tee_client_api: Correct max shared memory size define").
Plus some `uint32_t` => `size_t` cleanup.
> regression_5006: use 32KB buffers

- README.md
- host/xtest/Makefile
OP-TEE core configuration directive for AArch32 is `CFG_ARM32_core` not
`CFG_ARM32`.
> xtest: fix 32bit/64bit build directive when GP suite is enabled

- host/xtest/regression_4000.c
The documentation [1] for TEE_AEUpdate() states that "Unless one or
more calls of this function have supplied sufficient input data, no
output is generated". This can be understood as: "As soon as sufficient
input data have been supplied, some output is generated".
AES GCM effectively works as a stream cipher, so that any amount of
data passed to the algorithm should produce as much output data
immediately. In other words, calling TEE_AEUpdate() with N bytes of
input should generate N bytes of output for any N >= 1.
This commit updates regression_4005 to check the above assertion.
[1] GlobalPlatform TEE Internal Core API Specification v1.1
> Make sure AES GCM does not buffer data

- host/xtest/regression_4000.c
Similar to commit c13fafac91ae ("Make sure AES GCM does not buffer
data"), update regression_4003_NO_XTS to check that TEE_CipherUpdate()
does not not buffer data when algorithm is TEE_ALG_AES_CTR.
> Make sure AES CTR does not buffer data

- host/xtest/regression_1000.c
- ta/os_test/include/os_test.h
- ta/os_test/include/ta_os_test.h
- ta/os_test/os_test.c
- ta/os_test/ta_entry.c
This test case is derived from gp_8040 which was found to be failing on
HiKey with a preliminary version of the 64-bit pager enabled
(CFG_ARM64_core=y CFG_WITH_PAGER=y CFG_PAGED_USER_TA=y). This new
regression_1016 test fails in the same circumstances, but also when
paging is enabled in a 32-bit build of the TEE core.
> Add regression_1016: TA to TA buffer manipulations

- host/xtest/aes_perf.c
Insure input/output buffers are specified to a valid configuration
when aes_perf is called from xtest benchmark test entry.
Regported-by: Igor Opaniuk <igor.opaniuk@linaro.org>
Signed-off-by: Etienne Carriere <etienne.carriere@st.com>
> xtest: fix buffer setup in AES benchmark tests

- ta/aes_perf/ta_entry.c
Since ta/aes_perf/ta_entry.c uses EMSG() it must include the proper
header file.
> aes_perf: add missing #include <trace.h>

- host/xtest/include/uapi/linux/ion_old.h
- host/xtest/sdp_basic.c
Implement the old ION API using `ion0_`/`ION0_` as prefix.
Routine allocate_ion_buffer() attempts to allocate using the new
API. If the 1st request (query heap types) fails, try the old API.
> xtest:sdp: support old ION API if new API fails

- host/xtest/sdp_basic.c
Xtest crashes in 1014 when TEE core was built without SDP test pTA support (I.e `CFG_TEE_CORE_EMBED_INTERNAL_TESTS=n`).
Note: xtest 1014 is enabled only is `CFG_SECURE_DATA_PATH=y`.
> xtest:sdp: fix a xtest crash if TEE is built without test pTA

- host/xtest/regression_1000.c
- host/xtest/xtest_test.h
Keep a 80char/line alignment in regression_1000.c.
Info trace from xtest when regression 10xx test is skip because test materials (pTA) missing in TEE core.
Remove deprecated defines.
> Some minor cleaning in xtest

- Android.mk
To workaround the problem reported as following
when build OP-TEE with AOSP master:
external/optee_test/Android.mk: error: xtest: LOCAL_ADDITIONAL_DEPENDENCIES must only contain paths (not module names)
change to use $(OPTEE_BIN) defined in optee_os/mk/aosp_optee.mk
which is path like:
out/target/product/hikey/optee/arm-plat-hikey/core/tee.bin
as dependency for xtest instead of using the target of BUILD_OPTEE_OS
Reviewed-by: Victor Chong <victor.chong@linaro.org>
Tested by: Victor Chong <victor.chong@linaro.org> (hikey aosp)
Tested-by: Yongqin Liu <yongqin.liu@linaro.org> (hikey aosp master)
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
> Android.mk: change to use OPTEE_BIN instead of BUILD_OPTEE_OS

- host/xtest/Makefile
Due to an extra '@', 'make V=1' won't print the link command for xtest.
Fix that.
> xtest/Makefile: remove extra '@'

- host/xtest/regression_1000.c
Reduce the loop count in xtest 1012 from 1000 to 3 in order to minimize
debug traces. There is no point in using a higher value in this
functional test.
> Reduce loop count in regression_1012

- host/xtest/regression_4000.c
Adds a AES-CTR corner case to expose a problem in LTC with hardware
accelerated AES encryption.
The fix for the problem is provided in:
https://github.com/OP-TEE/optee_os/pull/2086
> 4003: add aes-ctr corner case

- ta/os_test/os_test.c
Test case for OP-TEE issue #2105 [1]: passing a NULL memref.buffer is
acceptable as long as memref.size is zero (GP Internal Core API
specification v1.1.2 section 4.9.4).
Link: [1] https://github.com/OP-TEE/optee_os/issues/2105
Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (QEMU)
> regression: 1006: test passing a NULL reference with 0 size

- Android.mk
- host/xtest/Makefile
- ta/include/ta_storage.h
- ta/storage/sub.mk
- ta/storage2/include/ta_storage.h
- ta/storage2/sub.mk
Since ta_storage.h is used by several TAs move it into a common
location.
> Move ta_storage.h to common location

- host/xtest/regression_6000.c
Update regression test 6007 to close and re-open the persistent object.
Reproducer for issue https://github.com/OP-TEE/optee_os/issues/2094.
From: Kevin Peng <kevinp@marvell.com>
> test_truncate_file_length(): close and re-open object

- Android.mk
Without `-Wno-missing-field-initializers`, GCC 4.9 generates below
errors, so add it to `Android.mk`. While we're at it, also add
`-Wno-format-zero-length` to sync with `host/xtest/Makefile`.
```
external/optee_test/host/xtest/regression_5000.c:485:40: error: missing field 'session' initializer [-Werror,-Wmissing-field-initializers]
struct xtest_session connection = { c };
^
external/optee_test/host/xtest/regression_2000.c:46:22: error: missing field 'paramTypes' initializer [-Werror,-Wmissing-field-initializers]
TEEC_Operation op = TEEC_OPERATION_INITIALIZER;
^
external/optee_test/host/xtest/xtest_helpers.h:43:40: note: expanded from macro 'TEEC_OPERATION_INITIALIZER'
^
external/optee_test/host/xtest/regression_2000.c:272:29: error: missing field 'session_id' initializer …
```
> Android.mk: workaround missing-field-initializers error

- host/xtest/regression_1000.c
- ta/os_test/os_test.c
This adds few test cases in regression test 1010 to check TA crash
when the TA is provided a memref as invocation parameter. These
tests aims at checking the dump of memref parameter state in sane
when core detect TA crash and dumps the TA state for debug purpose.
Refer to https://github.com/OP-TEE/optee_os/pull/2117 which should fix the issue.
The issue can be reproduced on Qemu using this test and the following config:
`make all run CFG_TEE_CORE_LOG_LEVEL=3 CFG_WITH_PAGER=y CFG_TEE_CORE_DEBUG=n CFG_CORE_TZSRAM_EMUL_SIZE=0x40000`
> regression 1010: crash TA with SHM memref passed as parameter

- host/xtest/regression_1000.c
Fix wrong format specifier, which causes build errors:
error: format '%d' expects argument of type 'int', but argument 4 has type
'size_t {aka long unsigned int}' [-Werror=format=]
"Invalid memory access %u with %d bytes memref",
`Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>`
> regression 1010: fix wrong printf format specifier

- CMakeLists.txt
- CMakeToolchain.txt
- host/xtest/CMakeLists.txt
- ta/CMakeLists.txt
This introduces support for building the host part (what's running in
linux user space) of xtest using CMake. TAs are as before built using TA
dev kit.
> Cmake support for xtest only (not TAs)

- ta/Makefile
- ta/aes_perf/Makefile
- ta/sdp_basic/Makefile
Don't include host_include/conf.mk when building the TA as many
unrelated variables are propagated. Some of those variables, for
instance, CFG_RESERVED_VASPACE_SIZE causes compile errors.
Relevant variables are already defined by the dev kit.
Needed by https://github.com/OP-TEE/optee_os/pull/2266
> ta: don't include host_include/conf.mk

- host/xtest/Makefile
Commit 950ea1cda6d3 ("regression: add case 8103") introduces a test that
needs OpenSSL to verify a certificate generated by a TA with Mbed TLS. It
updates xtest's CMakeLists.txt to link against OpenSSL when found, but the
regular Makefile is not updated.
This commit adds support for the new test to the non-CMake build by
linking xtest against the OpenSSL static library when CFG_TA_MBEDTLS=y.
> xtest: Makefile: link against OpenSSL if MBed TLS is enabled in TA

- host/xtest/regression_4000.c
- ta/crypt/include/seed_rng_taf.h
- ta/crypt/include/ta_crypt.h
- ta/crypt/seed_rng_taf.c
- ta/crypt/sub.mk
- ta/crypt/ta_entry.c
Add test case for testing system pTA functionality for seeding RNG pool.
Relates to: https://github.com/OP-TEE/optee_os/pull/2340
`Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>`
> crypto: add test case for seeding RNG pool

- host/xtest/Makefile
CFG_GP_PACKAGE_PATH is not expected to store 'y' but a path, if
defined. This change corrects the test on CFG_GP_PACKAGE_PATH regarding
OpenSSL depedency.
Fixes: 43d58a5fce8f ("xtest: Makefile: link against OpenSSL if MBed TLS is enabled in TA")
> xtest: Makefile: fix OpenSSL dependency on GP test suite support

- host/xtest/Makefile
Introduce build directive `OPTEE_OPENSSL_EXPORT` in GNU make script to get OpenSSL from the target rather than using the provided builds of the library.
> xest: OpenSSL may be provided by the system

- Android.mk
- host/xtest/regression_1000.c
so that we could make optee work with Treble enabled builds too
Acked-by: Victor Chong <victor.chong@linaro.org>
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
> Android.mk: make xtest installed in the vendor partition

- host/xtest/regression_1000.c
- host/xtest/regression_2000.c
- host/xtest/regression_4000.c
- host/xtest/regression_6000.c
- host/xtest/regression_7000.c
- host/xtest/regression_8000.c
Moves all ADBG_CASE_DEFINE() to right after the function implementing
the test case.
> regression_*.c: move ADBG_CASE_DEFINE()

- host/xtest/regression_1000.c
Test the "lockdep" algorithm. This simply triggers a special test
pseudo-TA.
> regression: add case 1020

- CMakeLists.txt
- ta/CMakeLists.txt
Without specify the TA header files are in C source file scope
cmake may attempt to look for resources as g++. When building
with environments that do not provide such tools as when building
from native buildroot ofr a qemu target, optee_client fails to
build. This change ensure a minimal C support allows to build
optee_client with cmake.
> ta: cmake: header files rely on C support

- host/xtest/adbg/src/adbg_run.c
- host/xtest/regression_4000.c
**(edited)**
Fix issues reported by GCC 8.1.0 with  `-Werror=stringop-overflow=.` **as reported per https://github.com/OP-TEE/optee_test/issues/296**.
**Issues also reported with a GCC 8.2.0 from a standard build command, i.e:
`make TA_DEV_KIT_DIR=path/to/devkit OPTEE_CLIENT_EXPORT=path/to/client-export`**
host/xtest/adbg/src/adbg_run.c:103:3: error: 'strncpy' specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
host/xtest/regression_4000.c:4986:3: error: 'memmove' pointer overflow between offset [0, 8] and size [4294967295, 2147483647] accessing array 'tmp' with type 'uint8_t[1024]' {aka 'unsigned char[1024]'} [-Werror=array-bounds]
Fixes issue https://github.com/OP-TEE/optee_test/issues/296
~~This change also adds test on buffer size output value to …
> xtest: prevent potential overflow

- host/xtest/regression_4000.c
Splits regression case 4007 into
- 4007_symmetric for symmetric keys
- 4007_rsa for RSA keys, which also is complemented with 3072 and 4096 keys
- 4007_dh for Diffie-Hellman keys
- 4007_ecc for ECC keys
> regression: split 4007 into key types

- host/xtest/adbg/src/adbg_run.c
"0 test cases were skipped" instead of "0 test case was skipped" after successful run
Signed-off-by: Markus S. Wamser <markus.wamser@mixed-mode.de>
> xtest: improve summary message

- host/xtest/regression_4000.c
- host/xtest/regression_4100.c
- host/xtest/regression_6000.c
Building optee_test with `cmake -DCMAKE_BUILD_TYPE=Release (...)` show errors reported by my GCC (8.2.0).
This P-R fixes the reported errors. The strange thing is that there are equivalent occurrences not reported by GCC, as the `obj{0|1|2}` in **[regression_6000.c](https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_6000.c#L1145)**. This P-R fixes only the one reported by GCC.
> Fix possibly uninitialized variable in regression tests

- CMakeLists.txt
- host/xtest/CMakeLists.txt
Build system can't find file_to_c.py and certificate files,
because CMakeLists.txt have an assumption about those files
locations. So, when you try to use separate build directory,
relative path in CMakeLists.txt are not working as expected.
It is better to use ${CMAKE_HOME_DIRECTORY} instead of assuming
that mentioned files can be reached from build directory.
Signed-off-by: Volodymyr Babchuk <vlad.babchuk@gmail.com>
> cmake: locate files WRT to project home directory

- ta/crypt/cryp_taf.c
ta_entry_copy_object_attributes() should faithfully returns
TEE_CopyObjectAttributes1()'s value instead of always overwriting it with
TEE_SUCCESS.
Signed-off-by: Oliver Chiang <rockerfeynman@gmail.com>
> ta/cryp_taf: correct return value

- Android.mk
- host/xtest/CMakeLists.txt
- host/xtest/Makefile
- host/xtest/stats.c
- host/xtest/stats.h
- host/xtest/xtest_main.c
Adds the --stats applet to interact with the pseudo TA "stats".
> xtest: add --stats applet

- host/xtest/regression_1000.c
When TAs are linked against shared versions of libutee etc., the
size of the main binary is reduced significantly. This causes test
1008.4 to fail, because the size of the TA drops from ~121 KiB down
to ~9 KiB which is smaller than the offset supplied to
load_corrupt_ta(). Use a smaller offest to fix the issue.
> regression 1008: adjust TA corruption test for CFG_ULIBS_SHARED=y

- ta/aes_perf/ta_aes_perf.c
- ta/concurrent/ta_entry.c
- ta/concurrent_large/ta_entry.c
- ta/crypt/aes_impl.c
- ta/crypt/aes_taf.c
- ta/crypt/cryp_taf.c
- ta/crypt/handle.c
- ta/crypt/mbedtls_taf.c
- ta/crypt/seed_rng_taf.c
- ta/crypt/sha2_impl.c
- ta/crypt/sha2_taf.c
- ta/crypt/ta_entry.c
- ta/os_test/include/testframework.h
- ta/os_test/os_test.c
- ta/rpc_test/ta_rpc.c
- ta/sdp_basic/ta_sdp_basic.c
- ta/sha_perf/ta_sha_perf.c
- ta/sims/ta_sims.c
- ta/socket/ta_entry.c
- ta/storage/storage.c
- ta/storage_benchmark/benchmark.c
This change initializes all local variables to prevent build issues
(warnings and/or errors) in OP-TEE test package. It uses TEE_MemFill()
to initialize structured and typed variables.
> TAs: explicitly initialize local variables

- host/xtest/adbg/src/adbg_case.c
- host/xtest/adbg/src/adbg_log.c
- host/xtest/adbg/src/adbg_run.c
- host/xtest/adbg/src/security_utils_hex.c
- host/xtest/aes_perf.c
- host/xtest/benchmark_1000.c
- host/xtest/install_ta.c
- host/xtest/regression_1000.c
- host/xtest/regression_2000.c
- host/xtest/regression_4000.c
- host/xtest/regression_4100.c
- host/xtest/regression_5000.c
- host/xtest/regression_6000.c
- host/xtest/regression_8000.c
- host/xtest/regression_8100.c
- host/xtest/sdp_basic.c
- host/xtest/sha_perf.c
- host/xtest/sock_server.c
- host/xtest/stats.c
- host/xtest/xml/include/xml_datastorage_api.h
- host/xtest/xml/include/xml_timearithm_api.h
- host/xtest/xtest_helpers.c
- host/xtest/xtest_helpers.h
- host/xtest/xtest_main.c
This change initializes all local variables to prevent build issues
(warnings and/or errors) in OP-TEE test package. It uses memset()
to initialize structured and typed variables.
This change replaces all TEEC_Session instance initialization from
= { 0 } into use of memset().
> xtest: Explicitly initialize local variables

- host/xtest/xml/include/xml_timearithm_api.h
Fixes a few errors when xtest is compiled with GP tests enabled
(CFG_GP_PACKAGE_PATH pointing to the GP Initial Configuration Test
Suite files).
Fixes: e4ec9e4aca08 ("xtest: Explicitly initialize local variables")
> GP: fix compile errors with calloc()

- host/xtest/CMakeLists.txt
- host/xtest/Makefile
Add -Wno-unsafe-loop-optimizations directive since regression_4100.c
fails to build on some recent toolchains as GCC 8.2 with a error
trace like:
/path/to/optee_test/host/xtest/regression_4100.c: In function ‘convert_from_string’:
/path/to/optee_test/host/xtest/regression_4100.c:448:8: error: missed loop optimization, the loop counter may overflow [-Werror=unsafe-loop-optimizations]
while (spos) {
^
/path/to/optee_test/host/xtest/regression_4100.c:455:6: error: missed loop optimization, the loop counter may overflow [-Werror=unsafe-loop-optimizations]
if (!spos)
^
The GNU Makefile build sequence defines -Wno-unsafe-loop-optimizations
for the whole xtest sources while CMake build sequence defines it
specifically for regression_4100.c among xtest source files.
Signed-off-by: Etienne …
> regression 41xx: prevent unsafe-loop-optimizations build error

- ta/miss/Android.mk
insert missing ".ta" at the end of filename
Fixes: 15cecff0 ("regression: add tests for panic events handling")
> ta/miss/Android.mk: fix typo

- host/xtest/regression_4000.c
- ta/crypt/derive_key_taf.c
- ta/crypt/include/derive_key_taf.h
- ta/crypt/include/ta_crypt.h
- ta/crypt/sub.mk
- ta/crypt/ta_entry.c
Adds test cases that tests the system pTA that derives device and TA unique keys.
This depends on https://github.com/OP-TEE/optee_os/pull/3053, which means that IBART will fail as long as optee_os:3053 hasn't been merged.
Note that I've only added two calls from xtest and do most testing in the ta_crypt TA function(s) itself. That makes it easy to write tests, but makes it less clear to understand what failed when something goes wrong. Having that said, I can split up `derive_ta_unique_key_test(...)` into a few more functions that will be called one by one from xtest separately if you think that is better. It'll be a bit more boiler plate code, but it's probably cleaner and would generate better output from xtest. Let me know what you think.
> regression 4013: add test for device and TA unique keys

- host/xtest/regression_1000.c
In regression test case 1010 xtest_tee_test_invalid_mem_access2()
allocates shared memory, but doesn't free it. This can affect other test
cases run after this case.
The shared memory is freed when the context is finalized, but that can
be too late since it normally happens when xtest exits.
> regression: fix memory leakage in case 1010

- ta/crypt/derive_key_taf.c
Use correct type size when printing size_t content and remove unused err
label.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
> ta/derive_key_taf: fix build warnings

- host/xtest/regression_1000.c
- ta/Makefile
- ta/os_test/Makefile
- ta/os_test/include/os_test.h
- ta/os_test/include/ta_os_test.h
- ta/os_test/os_test.c
- ta/os_test/ta_entry.c
- ta/os_test_lib_dl/Android.mk
- ta/os_test_lib_dl/Makefile
- ta/os_test_lib_dl/include/os_test_lib_dl.h
- ta/os_test_lib_dl/os_test_lib_dl.c
- ta/os_test_lib_dl/sub.mk
Adds a new test case for the dynamic link API in libdl.
- A new shared library is added in ta/os_test_lib_dl.
- In xtest 1022, the dl API is used to load the test library and
retrieve pointers to functions.
> Add regression 1022 to test dlopen()/dlsym()/dlclose()

- CMakeLists.txt
- host/xtest/CMakeLists.txt
When OpenSSL exists in a non-standard location, compilation
fails:
```bash
export OPENSSL_ROOT_DIR=/usr/local/openssl
cmake ...
make ...
| gcc  -Ihost/xtest/. -Ihost/xtest/adbg/include -Ihost/xtest/xml/include \
-I<user-ta>/host_include -Ihost/xtest -Ita/include \
-Ita/aes_perf/include -Ita/concurrent/include \
-Ita/concurrent_large/include -Ita/create_fail_test/include \
-Ita/crypt/include -Ita/enc_fs/include -Ita/os_test/include \
-Ita/rpc_test/include -Ita/sdp_basic/include -Ita/sha_perf/include \
-Ita/sims/include -Ita/miss/include -Ita/sims_keepalive/include \
-Ita/socket/include -Ita/storage_benchmark/include ... \
-DOPENSSL_FOUND=1 ... \
-MD -MT host/xtest/CMakeFiles/xtest.dir/regression_8100.c.o \
-MF host/xtest/CMakeFiles/xtest.dir/regression_8100.c.o.d \
-o …
```
> cmake: support OpenSSL in non-standard locations

- host/xtest/regression_1000.c
This PR contains a set of fixes in regression 1021 test which were mentioned in [PR#347](https://github.com/OP-TEE/optee_test/pull/347).
> regression 1021: fix wrong condition check

- host/xtest/regression_4000.c
As described in issue #363, this patch is to support a valid key rather than providing incorrect public part.
The comment states something true, X and Y are not used (otherwise the test would fail), but some implementations might check the validity of the point in order to accept populating the key.
> Set use of a valid public point for ECDSA operation in test 4009

- host/xtest/Makefile
COMPILE_NS_USER is used by the xtest Makefile to link against either
the 32-bit or 64-bit version of OpenSSL (libcrypto.a). Historically,
the top level Makefile of the OP-TEE build project would take
COMPILE_NS_USER as an input, with value 32 or 64, and derive the path
to the appropriate cross-compiler. But given that the cross-compiler
may also be customized via CROSS_COMPILE/CROSS_COMPILE_HOST,
inconsistencies can happen.
There is no reason to keep COMPILE_NS_USER, since its value can be
derived from the compiler itself. This commit adds macros to do just
that and uses them to select the proper libcrypto library.
Reported-by: Denys Dmytriyenko <denys@ti.com>
> xtest/Makefile: drop COMPILE_NS_USER and detect arch automatically

- ta/os_test/os_test.c
When dlopen() or dlsym() fail in regression test 1022, the error status
is set to TEE_ERROR_OUT_OF_MEMORY which is inappropriate since the true
cause of the error is unknown. Use TEE_ERROR_GENERIC instead. This is
essentially cosmetic to avoid confusion when debugging.
> regression 1022: return TEE_ERROR_GENERIC on failure

- host/xtest/regression_4100.c
convert_from_string() takes an hexadecimal character string and
converts it to binary. The size of the output buffer is computed from
the length of the input string, but the computation is wrong. Fix it.
> regression_4100.c: convert_from_string(): fix length of output buffer

- scripts/file_to_c.py
- scripts/rsp_to_gcm_test.py
use python3 instead of python as python2 is EOL January 2020.
Signed-off-by: Scott Branden <scott.branden@broadcom.com>
> use python3 instead of python

- host/xtest/aes_perf.c
- host/xtest/sha_perf.c
| host/xtest/aes_perf.c: In function 'aes_perf_run_test':
| host/xtest/aes_perf.c:473:11: error: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'time_t' {aka 'long long int'} [-Werror=format=]
|   473 |  vverbose("Clock resolution is %lu ns\n",
|       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|   474 |      ts.tv_sec * 1000000000 + ts.tv_nsec);
|       |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       |                             |
|       |                             time_t {aka long long int}
| host/xtest/crypto_common.h:56:11: note: in definition of macro '_verbose'
|    56 |    printf(__VA_ARGS__); \
|       |           ^~~~~~~~~~~
| host/xtest/aes_perf.c:473:2: note: in expansion of macro 'vverbose'
|   473 |  vverbose("Clock resolution is %lu …
> aes-perf, sha-perf: fix build with 64bit time_t on 32bit arches

- host/xtest/pkcs11_1000.c
Call `C_Finalize()` without prior `C_Initialize()`. Library shall return `CKR_CRYPTOKI_NOT_INITIALIZED`.
> pkcs11 1000: test finalize aginst non-initiated library

- .github/issue_template.md
- .github/pull_request_template.md
- .github/workflows/stale_issue.yml
Since "optee_os" and "build" both have reached an almost clean and up-to-date state, let's continue with adding templates and actions to the "optee_test" git also.
The GitHub templates and actions are useful to the "optee_test" git
also, therefore recursively sync up (copy) the .github folder from
build.git.
> GitHub: sync GitHub templates and actions from build.git

- host/xtest/sock_server.c
Free addrinfo obtained through getaddrinfo().
Otherwise, it results in resource leak.
Signed-off-by: Rajesh Ravi <rajesh.ravi@broadcom.com>
Signed-off-by: Scott Branden <scott.branden@broadcom.com>
> fix resource leak in sock_server_init

- Makefile
- scripts/checkpatch.sh
- typedefs.checkpatch
copied the checkpatch-helper scripts from optee_os repo
fixed README.md to reflect checkpatch targets still missing
Signed-off-by: Markus S. Wamser <markus.wamser@mixed-mode.de>
> add checkpatch scripts

- host/xtest/regression_1000.c
- ta/os_test/include/os_test.h
- ta/os_test/include/ta_os_test.h
- ta/os_test/os_test.c
- ta/os_test/ta_entry.c
- ta/os_test_lib/os_test_lib.c
- ta/os_test_lib_dl/os_test_lib_dl.c
Adds a test case for the ELF initialization functions (.init_array
section).
> Add regression 1023 (ELF initialization via .init_array)

- host/xtest/regression_1000.c
- host/xtest/sdp_basic.c
- host/xtest/sdp_basic.h
Depends on https://github.com/linaro-swg/linux/pull/61 (at least for the changes in regression 1018).
> Add outbound SHM and SDP memref case

- host/xtest/pkcs11_1000.c
Add test to list slots implemented by the PKCS11 TA and get information from. This change tests 
Cryptoki API functions `C_GetFunctionList()`, `C_GetInfo()`, `C_GetSlotList()` and `C_GetSlotInfo()`.
Depends on https://github.com/OP-TEE/optee_client/pull/190 and https://github.com/OP-TEE/optee_os/pull/3644.
> pkcs11 1001: get info from slots

- host/xtest/pkcs11_1000.c
* pkcs11 1001: split in sub tests
Define ADBG sub tests per tested API for the friendly traces generated by xtest.
* pkcs11 1001: get info from tokens
Get information from tokens implemented by the PKCS11 TA. This change tests Cryptoki API function C_GetTokenInfo().
Depends on https://github.com/OP-TEE/optee_os/pull/3656 and https://github.com/OP-TEE/optee_client/pull/192.
> pkcs11: test C_GetTokenInfo()

- host/xtest/pkcs11_1000.c
Check C_GetSlotList() returns CKR_BUFFER_TOO_SMALL, not CKR_OK when
called with a non-NULL ID buffer reference and a count info to ID.
Prior this change was this specific test not covered in case TA
implements more than 1 token.
> pkcs11 1001: test C_GetSlotList() for zero-count non-NULL buffer case

- ta/os_test/os_test.c
call_longjmp() does not return so it should have a __noreturn attribute.
Fixes a Clang warning:
$ make COMPILER=clang
...
CC      out/os_test.o
os_test.c:667:1: warning: function 'call_longjmp' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
{
^
> os_test: call_longjmp(): add __noreturn attribute

- host/xtest/pkcs11_1000.c
Rename xtest_tee_test_100x() into xtest_pkcs11_test_100x() for
consistency.
Fix a coding style alignment in test 1001.
> pkcs11 100x: rename tee_test into pkcs1_test

- host/xtest/regression_1000.c
- ta/os_test/include/os_test.h
- ta/os_test/include/ta_os_test.h
- ta/os_test/os_test.c
- ta/os_test/ta_entry.c
Add test 1025 verifying temporary memref of 0 bytes or NULL pointer
buffer conforming with:
GlobalPlatform Client API v1.0c (section 3.2.5 memory references), which
can be found at [1].
Link: [1] http://www.globalplatform.org/specificationsdevice.asp
Signed-off-by: Cedric Neveux <cedric.neveux@nxp.com>
> Allow memrefs with size 0

- host/xtest/regression_1000.c
Fix various spelling errors found in the 1xxx tests.
> xtest_1000.c: fix spelling errors

- host/xtest/regression_1000.c
Change regression test 1018 to allow any layer if the TEE invocation
channel to report outbound memory reference as long as it is the the
TA itself since outbound memory reference should be caught before the
TA is invoked by the TEE.
This change makes xtest regression test 1018 more flexible towards
changes in the OP-TEE components that can catch invalid memory reference
in invocation parameters depending on the OP-TEE configuration.
Fixes: 84382b31d3a3 ("regression 1018: add 1byte out of bounds reference test sub cases
")
Reported-by: Sumit Garg <sumit.garg@linaro.org>
> regression 1018: out of bounds memref tests ensure TA is not reached

- host/xtest/regression_1000.c
Skip regression test 1025 when TEE context reports that memref null
capability is not supported by the OP-TEE ecosystem. This change
prevents xtest suite to fail on regression 1025 when one tests
the latest optee_os/optee_client/optee_test that supports this recent
capability with a mainline or older Linux kernel that does not yet
support this feature.
Reported-by: Masami Hiramatsu <masami.hiramatsu@linaro.org>
> regression 1025: skip test if memref null capability not supported

- host/xtest/regression_1000.c
Add a conformance test to check `TEEC_RegisterSharedMemory()` refuses to register
a NULL buffer as a shared memory reference as per GPD TEE specification.
This test currently fails as optee_client needs to be fixed. Fix proposal in https://github.com/OP-TEE/optee_client/pull/204.
> regression_1025: test registering of NULL buffer as shared memory

- host/xtest/pkcs11_1000.c
> Pkcs11 login

- host/xtest/regression_4000.c
Some DSA tests are currently run at level 1 or higher (xtest -l 1).
But, since optee_os commit xxxxx, the DSA key generation is much faster
so there is no reason to exclude test cases from the default level.
> regression 4007_dsa: run all tests at level 0

- host/xtest/regression_4000.c
From [comment r39709](https://github.com/OP-TEE/optee_test/pull/396/commits/c9f22a91dd896972a43180b157f989360810ae1e#r397095605), this P-R superseeds https://github.com/OP-TEE/optee_test/pull/396.
```
Add check of array boundaries in xtest_tee_test_4011()
to prevent any overrun.
Signed-off-by: Rajesh Ravi <rajesh.ravi@broadcom.com>
Signed-off-by: Scott Branden <scott.branden@broadcom.com>
[ec: log error with adbg macro, s/</<=/]
```
> regression 4000: prevent array overrun in xtest_tee_test_4011

- host/xtest/regression_1000.c
- host/xtest/xtest_uuid_helpers.c
- host/xtest/xtest_uuid_helpers.h
Tests 1027 and 1028 depend on xtest_uuid_v5() which in turn depends on OpenSSL
APIs so they should just return if OPENSSL_FOUND is not defined.
> xtest: disable tests 1027 and 1028 if no OpenSSL

- host/xtest/Makefile
As more tests use or depend on OpenSSL, it does not make sense anymore
to enable OpenSSL, i.e. define OPENSSL_FOUND, based on one or several or
all of the 'imported' CFG* flags. Instead, decouple the definition of
OPENSSL_FOUND from CFG* flags and use a local WITH_OPENSSL flag instead.
This will allow CI testing of builds without OPENSSL_FOUND.
Suggested-by: Jerome Forissier <jerome@forissier.org>
> xtest: Makefile: create flag to enable OpenSSL

- ta/os_test/os_test.c
Fix build warning reported with trace below:
os_test.c: In function ‘ta_entry_client_identity’:
os_test.c:1220:21: warning: unused variable ‘propset’ [-Wunused-variable]
TEE_PropSetHandle *propset = NULL;
^~~~~~~
> ta: os_test: fix build warning on unused propset

- host/xtest/regression_1000.c
Fix build warning reported with trace message like below:
.../optee-test-custom/host/xtest/regression_1000.c:2049:20: error: ‘client_uuid_linux_ns’ defined but not used [-Werror=unused-variable]
static const char *client_uuid_linux_ns = "58ac9ca0-2086-4683-a1b8-ec4bc08e01b6";
^~~~~~~~~~~~~~~~~~~~
Fixes: 8e070bc41e1d ("xtest: disable tests 1027 and 1028 if no OpenSSL")
> xtest: regression 1027: fix build warning when openssl not used

- host/xtest/regression_4000.c
- ta/crypt/include/ta_crypt.h
- ta/crypt/ta_entry.c
Fix misspelling of "random number generate" command in the 'crypt' TA.
> xtest: fix spelling error in the 'crypt' TA

- ta/os_test/include/user_ta_header_defines.h
- ta/os_test/os_test.c
Added tests related to https://github.com/OP-TEE/optee_os/pull/3886.
> xtest regression 1006: add tests on binary block properties

- host/xtest/pkcs11_1000.c
Test C_CreateObject() and C_DestroyObject() over basic objects.
Co-developed-by: Etienne Carriere <etienne.carriere@linaro.org>
Depends on:
https://github.com/OP-TEE/optee_os/pull/3835
https://github.com/OP-TEE/optee_client/pull/209
> pkcs11_1000: test C_CreateObject() and C_DestroyObject()

- ta/os_test/os_test.c
When using Clang on HiKey (tested with 9.0.1 and 10.0.0), xtest 1023
fails with:
* regression_1023 Test ELF initialization (.init_array)
regression_1000.c:1860: Expression "op.params[0].value.a == 21" (12 == 21) is false
regression_1000.c:1871: Expression "op.params[0].value.a == 213" (123 == 213) is false
regression_1023 FAILED
The values indicate that the os_test_lib shared library is initialized
after the main application, which is not what we expect. In fact, the
reason for the failure is code elimination performed by Clang [1]. The
validity of this optimization is still unclear, but in any case it does
not concern the main things being tested, which is the invocation of
initialization functions when they exist. Therefore this commit applies
a workaround which effectively disables the …
> regression 1023: workaround Clang optimization issue

- ta/os_test/os_test.c
Fix build warning reported with trace below:
os_test.c: In function ‘check_binprop_ones’:
os_test.c:62:14: warning: pointer targets in passing argument 1 of ‘strncmp’ differ in signedness [-Wpointer-sign]
if (strncmp(bbuf, ones, bblen)) {
^~~~
In file included from os_test.c:10:
/local/home/frq93142/Projects/linaro-optee-3.9.0/optee_os/out/arm/export-ta_arm32/include/string.h:23:5: note: expected ‘const char *’ but argument is of type ‘uint8_t *’ {aka ‘unsigned char *’}
int strncmp(const char *s1, const char *s2, size_t n);
^~~~~~~
os_test.c:62:20: warning: pointer targets in passing argument 2 of ‘strncmp’ differ in signedness [-Wpointer-sign]
if (strncmp(bbuf, ones, bblen)) {
^~~~
In file included from os_test.c:10:
/local/home/frq93142/Projects/linaro-optee-3.9.0/optee_os/out/arm/export …
> ta: os_test: fix build warning in binary property tests

- ta/os_test/sub.mk
os_test includes C++ exception tests which are incompatible with ftrace
by design [1]. This commit makes sure the C++ tests are not compiled
with the profiling flag (-pg), which is the flag that one would use to
enable function tracing in TAs.
Link: [1] https://github.com/OP-TEE/optee_os/issues/4022
> os_test: C++: disable profiling (-pg)

- .github/workflows/stale_issue.yml
Sync the GitHub workflow file with the recent changes in optee_os as
described in [1] with the difference that we use a more recent version
of the "actions/stale" workflow (v3.0.10). In short, this updates the
version and add "bug" and "enhancement" as the labels where the GitHub
bot shouldn't mark an issue or pull request as stale ticket.
Link: [1] https://github.com/OP-TEE/optee_os/commit/50bbda3dd3
> github: update actions/workflow file

- host/xtest/regression_1000.c
- ta/os_test/os_test.c
- ta/os_test/sub.mk
- ta/os_test/ta_entry.c
- ta/os_test_lib/include/os_test_lib.h
- ta/os_test_lib/os_test_lib.c
Addresses https://github.com/OP-TEE/optee_os/pull/4008#issuecomment-675512429.
> Disable TLS/C++ tests with some unsupported compilers

- ta/os_test/os_test.c
- ta/os_test/sub.mk
- ta/os_test/ta_entry.c
- ta/os_test_lib/include/os_test_lib.h
- ta/os_test_lib/os_test_lib.c
This reverts commit 30efcbeaf8864d0f2a5c4be593a5411001fab31b.
Now that R_AARCH64_TLSDESC relocations are implemented in OP-TEE [1]
there is no need to make an exception for older GCC versions.
[1] https://github.com/OP-TEE/optee_os/commit/7bc927fa5192f4af4f59072f38822e0082e4bddb
> Revert "os_test: arm64: disable C++ and TLS tests depending on compiler"

- host/xtest/regression_6000.c
The flag TEE_DATA_FLAG_OVERWRITE is not permitted with the
TEE_OpenPersistentObject() functions. So remove the flag where needed in
the 6020 case.
> regression 6020: fix fs_open() flags

- ta/crypt/cryp_taf.c
- ta/storage/include/user_ta_header_defines.h
- ta/storage/storage.c
> Gp 1.1 annotation

- ta/crypt/cryp_taf.c
Prior to this patch there was a warning in unpack_attrs():
cryp_taf.c: In function ‘unpack_attrs’:
cryp_taf.c:344: warning: "TEE_ATTR_BIT_VALUE" redefined
#define TEE_ATTR_BIT_VALUE    (1 << 29)
In file included from /home/jens/work/op-tee/out-os-qemu/export-ta_arm32/include/tee_api.h:12,
from /home/jens/work/op-tee/out-os-qemu/export-ta_arm32/include/tee_internal_api.h:10,
from cryp_taf.c:7:
/home/jens/work/op-tee/out-os-qemu/export-ta_arm32/include/tee_api_defines.h:282: note: this is the location of the previous definition
#define TEE_ATTR_BIT_VALUE  TEE_ATTR_FLAG_VALUE
Fix this by removing the now deprecated TEE_ATTR_BIT_VALUE define.
> ta/crypt: fix warning in unpack_attrs()

- CMakeLists.txt
- host/xtest/Makefile
- host/xtest/gp/include/xml_client_api.h
- host/xtest/gp/include/xml_crypto_api.h
- host/xtest/gp/include/xml_datastorage_api.h
- host/xtest/gp/include/xml_internal_api.h
- host/xtest/gp/include/xml_timearithm_api.h
- host/xtest/install_ta.c
- host/xtest/regression_4100.c
- host/xtest/regression_8100.c
- host/xtest/stats.c
xtest (the 'host' part, not the TAs) uses __unused from OP-TEE's
<compiler.h>. This does not comply with the following statement from
the C specification:
In addition to the names documented in this manual, reserved names
include all external identifiers (global functions and variables)
that begin with an underscore (‘_’) and all identifiers regardless of
use that begin with either two underscores or an underscore followed
by a capital letter are reserved names. This is so that the library
and header files can define functions, variables, and macros for
internal purposes without risk of conflict with names in user
programs.
This is not a hypothetical problem, __unused is used by musl and as
optee-test can't be built with musl.
<compiler.h> and __unused should only be used in TAs (in which …
> xtest: remove __unused and do not include <compiler.h>

- host/xtest/adbg/include/adbg.h
Prior to this patch was the order of the cases depending on link order
and in which order constructors are called inside an object file. To use
a well defined order, sort the cases while registering them.
> xtest: sort cases to use a well defined order

- host/xtest/regression_4000.c
Test 4007_dh was found to fail occasionally when the core crypto
library is MBed TLS, but not with LibTomCrypt. It is because the OP-TEE
custom DH key generation in LibTomCrypt has a bug [1]: it always sets
bit 'xbits' when xbits != 0, and the tests do verify this property.
This patch changes the key size test so that it checks that the byte
size of the private key is smaller or equal to the requested key size,
not strictly equal.
This change also impacts other algorithms than DH, although no failure
have been found with them. But what garantee do we have that a n-bit
private key should always have a non-zero top n/8th byte?
To reproduce the failure with MBed TLS prior to this patch:
$ make CFG_CRYPTOLIB_NAME=mbedtls CFG_CRYPTOLIB_DIR=lib/libmbedtls
QEMU $ while [ $? -eq 0 ]; do xtest -l …
> Fix key size tests (from == to <=)

- host/xtest/regression_8100.c
- host/xtest/stats.c
Mark unused params to avoid build warnings/errors.
> xtest: mark unused params

- host/xtest/regression_1000.c
Test 1008 runs a negative test for TEEC_OpenSession() 100 times in a
loop. A comment says it is to check for memory leaks, but it is a bit
pointless because there is no guarantee that such a leak would be
detected this way. xtest is a functional test suite, not a stress test
tool so this kind of test is not really appropriate. It increases the
execution time and the amount of logs produced for very little benefit.
Therefore, remove the loop and test the open session failure only once.
> regression 1008: only test open session failure once

- host/xtest/pkcs11_1000.c
Add test case for checking that a call to C_SignUpdate()/
C_VerifyUpdate() with valid input buffer and size as 0 returns
no error and has no effect on output result.
> xtest: pkcs11: Add test case for C_SignUpdate()/C_VerifyUpdate()

- host/xtest/regression_4000.c
Adds test for TEE_CopyOperation() in the 4003 in the same way as we have
for 4001 and 4002.
Signed-off-by: Tony He <tony.he@armchina.com>
Depends on https://github.com/OP-TEE/optee_os/pull/4268 for tests to pass.
> regression 4003: test TEE_CopyOperation()

- host/xtest/pkcs11_1000.c
When trying to open session without CKF_SERIAL_SESSION method should fail
with CKR_SESSION_PARALLEL_NOT_SUPPORTED.
Specified in:
PKCS #11 Cryptographic Token Interface Base Specification Version 2.40
Plus Errata 01
5.6 Session management functions
C_OpenSession
> xtest: pkcs11: Fix parallel session test

- ta/os_test/os_test.c
Enables bget test if CFG_TA_BGET_TEST=y.
Runs the test from https://github.com/OP-TEE/optee_os/pull/4293
> ta/os_test: add bget test

- host/xtest/regression_1000.c
```
pTA UUID which used for SDP tests is PTA_INVOKE_TESTS_UUID`, which points
to a different "invokes_tests.pta", not "sdp.pta".
Rename it to avoid future confusion.
Signed-off-by: Igor Opaniuk <igor.opaniuk@gmail.com>
```
> xtest: regression 1014: rename pTA name used in SDP tests

- host/xtest/pkcs11_1000.c
PKCS#11 specification states that :
When C_Logout successfully executes, any of the application’s
handles to private objects should become invalid (even if a user
is later logged back into the token, those handles remain invalid).
In addition, all private session objects from sessions belonging
to the application should also be destroyed.
One of the find sub-test case was expecting that after logging back
in a session , private session object would be visible which was
a wrong assumption. This has been modified.
Another subcase assumed the handle of the token object returned
would be same as that when the token object was created by that
session. This assumption would hold good only during the first
log in into this session. If a user logs out and then logs in
again, the token object …
> xtest: pkcs11: Modify testcase 1011 for changes in C_Logout()

- Android.mk
Rearrange some code segments to make Android.mk more in sync with
host/xtest/Makefile and improve legibility.
xtest_uuid_helpers.c is also missing from 'srcs' so add that too.
> Android.mk: improve legibility

- host/supp_plugin/Makefile
- host/xtest/regression_1000.c
- ta/os_test/os_test.c
With integration of 01f6f06 ("regression: add tests for the supplicant plugin framework") builds started failing in Yocto.
This PR fixes the issue and also silences older warning.
> Fix failing build

- host/xtest/gp/include/xml_client_api.h
Fixes a multitude of warnings emitted for the function
TEEC_initialize_memory() when compiling for a 32-bit target.
In file included from gp_10000.c:21:
gp_10000.c: In function ‘gp_test_teec_10023’:
gp/include/xml_client_api.h:272:17: error: comparison of integer expressions of different signedness: ‘long int’ and ‘unsigned int’ [-Werror=sign-compare]
272 |   if ((long)shm != IGNORE) {\
|                 ^~
gp_10000.c:318:5: note: in expansion of macro ‘TEEC_initialize_memory’
318 |     TEEC_initialize_memory(SHARE_MEM01, IGNORE, OFFSET_02, SIZE_02, BYTE_01, BYTE_02, BYTE_03);
|     ^~~~~~~~~~~~~~~~~~~~~~
> gp: fix warning in TEEC_initialize_memory()

- host/xtest/pkcs11_1000.c
Earlier it was wrongly assumed that size (CKA_VALUE_LENGTH)
of CKK_GENERIC_SECRET object has to be in bits. This is
not correct as CKA_VALUE_LENGTH is the key size in bytes.
Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>
Reviewed-by: Vesa Jääskeläinen <vesa.jaaskelainen@vaisala.com>
> xtest: pkcs11: Fix size of Generic Secret Key

- host/xtest/pkcs11_1000.c
When creating object of type CKO_GENERIC_SECRET using
C_CreateObject(), CKA_VALUE is mandatory attribute in the
template and CKA_VALUE_LENGTH should not be provided. This
check was added in the implementation recently so the template
need to be corrected.
Also add an additional check to confirm that CKA_VALUE_LENGTH
gets populated correctly by the TA when such objects are created.
This depends on 
https://github.com/OP-TEE/optee_os/pull/4465
> xtest: pkcs11: Correct template for secret key

- host/xtest/gp/include/xml_datastorage_api.h
GP tests 30125 (9d-21-98) and 30127 (9d-28-5d) use badly encoded
constants: TEE_ATTR_RSA_PUBLIC_EXPONENT_VALUE_GEN_NOT_ODD (= 65538)
TEE_ATTR_RSA_PUBLIC_EXPONENT_VALUE_NOT_GEN_DEFAULT (= 66001),
respectively.
The values are given in decimal in the test suite documentation and
were erroneously encoded in little endian order in source file
host/xtest/gp/include/xml_datastorage_api.h.
Fix the values by using big endian encoding as expected by the GP API
when big numbers are provided as input to crypto functions.
Fixes the failure of "xtest gp_30125" after OP-TEE OS commit [1] (prior
to that commit, both the code and the test were wrong).
Link: [1] https://github.com/OP-TEE/optee_os/commit/c9366c1eeaa1c3dcecafeb03bef24e9e6fc660c4
> gp: fix endianness of two RSA public exponents

- host/xtest/stats.c
Fix trace message in pager stats: "Available physical pages" is in fact
the number of unlocked pages in pager pool while "Faults" is in fact
the overall number of pages in pager page pool.
Reported-by: Timothée Cercueil <timothee.cercueil@st.com>
> xtest: stats: fix trace on pager stats

- host/xtest/CMakeLists.txt
Define CFG_PKCS11_TA macro in xtest source compilation when
CFG_PKCS11_TA=y unless what build fails when optee_test is built with
CFG_PKCS11_TA=y while optee_os was built without.
Fixes: https://github.com/OP-TEE/optee_os/issues/4550
> xtest: CMake: enable CFG_PKCS11_TA when building with CFG_PKCS11_TA=y

- host/xtest/Makefile
Was seeing below issue when compiling with CFG_PKCS11_TA=y
make CFG_ARM64=y CFG_PKCS11_TA=y OPTEE_CLIENT_EXPORT=/home/optee_client_github/out/export/usr/ TA_DEV_KIT_DIR=/home/optee_os_github/out/arm-plat-ls/export-ta_arm64
make[1]: Entering directory '/home/optee_test_github/host/xtest'
CC      /home/optee_test_github/host/xtest/regression_1000.c
cc1: error: ../../../optee_client/libckteec/include: No such file or directory [-Werror=missing-include-dirs]
cc1: all warnings being treated as errors
Makefile:162: recipe for target '/home/optee_test_github/out/xtest/regression_1000.o' failed
make[1]: *** [/home/optee_test_github/out/xtest/regression_1000.o] Error 1
make[1]: Leaving directory '/home/optee_test_github/host/xtest'
Makefile:38: recipe for target 'xtest' failed
make: *** [xtest] …
> xtest: make: fix make when optee_test and optee_client are not in same directory with CFG_PKCS11_TA=y

- host/xtest/gp/patches/0012-TTA_TCF-remove-TEE_MemMove-from-CmdTEEGetPropertyAsX.patch
Add a patch to fix a bug in CmdTEEGetPropertyAsXXX_fromEnum(). Fixes
gp_20036 on QEMUv8 with OP-TEE's ftrace enabled, i.e.:
make CFG_FTRACE_SUPPORT=y CFLAGS_ta_arm64=-pg run
Fixes: https://github.com/OP-TEE/optee_os/issues/4561
> gp: fix CmdTEEGetPropertyAsXXX_fromEnum()

- host/xtest/gp/patches/0013-Disable-Invoke_GetTAPersistentTimeNotSet_and_SetTAPe.patch
Add a patch to exclude ce-7b-17 from the test suite since OP-TEE does
not provide the necessary external command to erase TA persistent time.
Note that skipping a test will shift the numbering in the "gp" suite,
so after this patch gp_40178 will be the same as gp_40179 prior to the
patch.
Fixes: https://github.com/OP-TEE/optee_test/issues/510
> gp: disable test ce-7b-17 (gp_40178)

- Makefile
Follow change done in optee_client which now installs
optee_client_config.mk in the include directory by default.
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
> Makefile: use the updated path for optee_client_config.mk

- host/xtest/regression_4000.c
Hello,
@jforissier
The test to add is in the end very simple ... just one `XTEST_MAC_CMAC_CASE` :)
Should I specify in the commit message, that it's related to the CAAM? I don't know if I should since this test is generic and the CAAM platform specific ..
Please refer to https://github.com/OP-TEE/optee_os/pull/4583
Thanks
> regression 4002: add CMAC test case with a 16 bytes increment

- ta/storage_benchmark/benchmark.c
During Storage benchmark testing.
When we try to Open persistent object with following flags:
TEE_DATA_FLAG_ACCESS_READ | TEE_DATA_FLAG_ACCESS_WRITE |
TEE_DATA_FLAG_ACCESS_WRITE_META | TEE_DATA_FLAG_OVERWRITE
which lands into syscall_storage_obj_open(), where it checks the flags
which were passed during opening the object and valid flags
TEE_DATA_FLAG_ACCESS_READ | TEE_DATA_FLAG_ACCESS_WRITE |
TEE_DATA_FLAG_ACCESS_WRITE_META | TEE_DATA_FLAG_SHARE_READ |
TEE_DATA_FLAG_SHARE_WRITE
TEE_DATA_FLAG_OVERWRITE flag is not a valid flag in
TEE_OpenPersistentObject(), thats why this call will always
fail.
Removing TEE_DATA_FLAG_OVERWRITE in call to TEE_OpenPersistentObject
Signed-off-by: Sahil Malhotra <sahil.malhotra@nxp.com>
Fixes: https://github.com/OP-TEE/optee_os/issues/4659
> benchmark: remove TEE_DATA_FLAG_OVERWRITE in call to TEE_OpenPersistentObject

- host/xtest/Makefile
- host/xtest/regression_1000.c
- host/xtest/xtest_test.c
- host/xtest/xtest_test.h
- ta/CMakeLists.txt
- ta/large/Android.mk
- ta/large/Makefile
- ta/large/include/ta_large.h
- ta/large/include/user_ta_header_defines.h
- ta/large/sub.mk
- ta/large/ta_entry.c
Adds the case 1034 which tests loading a large TA to see that the pager
can manage initialized read-only pages spanning two translation tables.
Needs https://github.com/OP-TEE/optee_os/pull/4628 to pass reliably with paging enabled.
> regression: add case 1034 with a large TA

- host/xtest/regression_1000.c
Now that the kernel feature required by tests 1027 and 1028 is upstream,
provide the commit SHA-1 and link to it.
> regression 1027, 1028: update comment about required kernel commit

- host/xtest/regression_1000.c
Disabled the large TA part of 1013 and large TA test 1034
when virtualization is enabled since it uses too much secure heap.
For QEMU environment, enough secure memory is not available
for each guest, so these testcases fail when CFG_VIRTUALIZATION=y
> xtest : disable large TA tests with virtualization

- ta/Makefile
Add large TA to the list of the TAs built from ta/Makefile which
change was missing from [1].
Link: [1] 94fb1581e071 ("regression: add case 1034 with a large TA")
Reported-by: Christophe Priouzeau <christophe.priouzeau@st.com>
> regression: add large TA to  build lists in Makefile

- host/xtest/regression_8100.c
va_list ap is undefined after a call to vsnprintf, so need
to put va_start and va_end before and after every vsnprintf.
Otherwise, the content of str buffer may be messed up.
Signed-off-by: Jingdong Lu <jingdong.lu@intel.com>
> regression 8102, 8103: change myasprintf implementation

- host/xtest/pkcs11_1000.c
It is possible that when querying memory that return buffer for signature
size does not have any meaningful value.
It has been observed that some PKCS#11 libraries does not initialize the
memory to zero and it is also completely fine based on specification.
Add test for the case so that it does not regress in future.
Specified in:
PKCS #11 Cryptographic Token Interface Base Specification
Version 2.40 Plus Errata 01
5.2 Conventions for functions returning output in a variable-length buffer
Related PRs:
- https://github.com/OP-TEE/optee_client/pull/273
> xtest: Add more tests for querying signature size for C_Sign/C_SignFinal

- host/xtest/pkcs11_1000.c
Test that querying size for CK_ULONG works.
Related PRs:
- https://github.com/OP-TEE/optee_client/pull/274
> xtest: Add test for querying CK_ULONG size

- host/xtest/pkcs11_1000.c
When secret object's properties are not protected make sure that they can
be read normally.
When they are protected make sure that proper error values are reported:
- C_GetAttributeValue return value is CKR_ATTRIBUTE_SENSITIVE
- For field that is protected size is CK_UNAVAILABLE_INFORMATION
Specified in:
PKCS #11 Cryptographic Token Interface Base Specification
Version 2.40 Plus Errata 01
C_GetAttributeValue
> xtest: Verify that sensitive information is protected

- host/xtest/regression_1000.c
Same fix than commit fbdc175bb9f3 ("xtest 1013: ignore out of memory
errors on large TA") for regression test 1034.
> xtest 1034: ignore out of memory errors on large TA

- host/xtest/pkcs11_1000.c
Add test cases to test calling of:
- C_WrapKey
- C_UnwrapKey
> xtest: pkcs11: Add tests for wrap/unwrap operations

- host/xtest/pkcs11_1000.c
Verify that CKR_BAD_ARGUMENT is reported properly for:
- C_EncryptFinal with invalid arguments
- C_DecryptFinal with invalid arguments
Test here is expected to fail always with same error so check for that and
then clear the error code so that only expected return value is checked.
Relates to:
- https://github.com/OP-TEE/optee_os/issues/4283
Related PR:
- https://github.com/OP-TEE/optee_client/pull/276
> xtest: pkcs11: Verify that bad arguments is reported for cipher finals

- host/xtest/pkcs11_1000.c
Tests that C_EncryptInit intiializes operation and calling it twice does
not terminate it.
Relates to:
- https://github.com/OP-TEE/optee_os/issues/4283
Related PRs:
- https://github.com/OP-TEE/optee_os/pull/4756
> xtest: pkcs11: Add test for calling C_EncryptInit twice

- host/xtest/regression_1000.c
- ta/os_test/os_test.c
Check that TEE_Malloc() returns a non-NULL pointer when requested size
is zero and that the returned pointer is inaccessible for read or write.
Testing feature introduced in optee_os commit a83ee50a8047 ("libutee:
Handle zero sized buffer allocations") [1].
Link: https://github.com/OP-TEE/optee_os/commit/a83ee50a8047
> regression 1010: test zero-size TEE_Malloc()

- host/xtest/pkcs11_1000.c
Add tests for CKM_AES_CMAC* mechanisms.
> xtest: pkcs11: Add tests for AES CMAC mechanisms

- host/xtest/pkcs11_1000.c
Add test for verifying X.509 certificate import.
Relates to:
- https://github.com/OP-TEE/optee_os/issues/4283
Related PRs:
- https://github.com/OP-TEE/optee_os/pull/4797
- https://github.com/OP-TEE/optee_client/pull/283
- https://github.com/OP-TEE/optee_client/pull/287
> xtest: pkcs11: Add X.509 certificate tests

- host/xtest/pkcs11_1000.c
Fix generic secret key test corrupted by commit [1] that changed
cktest_mac_cases[] first cell and made an AES_CMAC operation used by test
pcsk11_ to sign data with a generic secret key which is not allowed.
Let's define defining specific test data for pkcs11_1010 rather than
reuse cktest_mac_cases[] content which is dedicated to HMAC tests
(pkcs11_1008) and CMAC tests (pkcs11_1009).
Fixes: [1] da1e3aaa8e0f ("xtest: pkcs11: Add tests for AES CMAC mechanisms")
> pkcs11 1010: Fix generic secret key test

- Android.mk
otherwise it will report build error like this:
12:16:49 [ 48% 267/555] including external/optee_test/Android.mk ...
12:16:49 FAILED:
12:16:49 external/optee_test/Android.mk:19: error: scripts/common.mk: No such file or directory
12:16:49 04:16:49 ckati failed with: exit status 1
which is reported here:
https://ci.linaro.org/job/android-lcr-reference-hikey960-q/129/console
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
Reviewed-by: Victor Chong <victor.chong@linaro.org>
> Android.mk: specify scripts/common.mk path with $(LOCAL_PATH)

- host/xtest/sdp_basic.c
Close file descriptor before returning when failing to read
from /dev/urandom.
Fixes: 41343db4 ("xtest: add SDP basic tests")
Signed-off-by: Cyrille Fleury <cyrille.fleury@nxp.com>
> xtest: sdp: fix resource leak in get_random_bytes

- ta/os_test_lib/sub.mk
- ta/os_test_lib_dl/sub.mk
Disable the compilation of C++ files from os_test_lib
and is_test_lib_dl if C++ tests are disabled i.e xtests
are built with option WITH_CXX_TESTS=n.
> Disable C++ file compilation WITH_CXX_TESTS=n

- .github/workflows/stale_issue.yml
- Update 'stale' from v3.0.10 to v4.0.1.
- Give 'write' permissions to actions (pull requests and issues).
- Add and set (to true)
remove-issue-stale-when-updated
remove-pr-stale-when-updated
which will automatically remove the 'Stale' label when someone adds a
new comment to a ticket marked as stale.
Fixes: https://github.com/OP-TEE/optee_test/issues/576
> GitHub actions: General updates

- host/xtest/Makefile
- host/xtest/regression_1000.c
- host/xtest/xtest_test.c
- host/xtest/xtest_test.h
- ta/CMakeLists.txt
- ta/Makefile
- ta/bti_test/Android.mk
- ta/bti_test/Makefile
- ta/bti_test/bti_stubs_a64.S
- ta/bti_test/include/ta_arm_bti.h
- ta/bti_test/include/ta_arm_bti_priv.h
- ta/bti_test/include/user_ta_header_defines.h
- ta/bti_test/sub.mk
- ta/bti_test/ta_arm_bti.c
- ta/bti_test/ta_entry.c
Check that not having appropriate bti launchpads when using
br or blr results in exception getting generated.
Reviewed-by: Jerome Forissier <jerome@forissier.org>
> regression: Add test case 1035 for testing bti

- host/xtest/gp/include/xml_crypto_api.h
```
Reset saved IV parameters after test when test case passes no IV.
Otherwise, the values from the previously run test would be re-used,
possibly causing an error due to incompatibility with other parameters
(such as the algorithm requiring no IV). This bug was revealed by
optee_os PR#5087 [1]:
$ xtest 50163
Test ID: 50163
[...]
* gp_50163 50-c6-0b
gp_50163 OK
[...]
$ xtest 5016 -x 50160 -x 50161  -x 50164 -x 50165 -x 50166 -x 50167 \
-x 50168 -x 50169
[...]
* gp_50162 50-d8-77
gp_50162 OK
* gp_50163 50-c6-0b
gp/include/xml_crypto_api.h:2618: res = cipher_do_final(c, s, full_data, fulld_length, & full_ciphered_data) has an unexpected value: 0xffff3024 = TEE_ERROR_TARGET_DEAD, expected 0x0 = TEEC_SUCCESS
gp_50000.c:3768: Invoke_Crypto_CipherDoFinal(c, SESSION01, 0x0001000E, 1, …
```
> gp: fix Invoke_Crypto_CipherInit()

- host/xtest/regression_1000.c
Since optee_os commit c6b34ea8d5b5 ("core: fix build dependencies for
fs_htree.c") [1], the fs_htree tests are disabled in the test PTA unless
CFG_REE_FS=y. Therefore do the same thing in xtest.
Fixes the following error:
$ CFG_REE_FS=n CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y run
[...]
$ xtest 1015
[...]
* regression_1015 FS hash-tree corner cases
regression_1000.c:1293: TEEC_InvokeCommand(&session, 6, ((void *)0), &ret_orig) has an unexpected value: 0xffff0006 = TEEC_ERROR_BAD_PARAMETERS, expected 0x0 = TEEC_SUCCESS
regression_1015 FAILED
Link: [1] https://github.com/OP-TEE/optee_os/commit/c6b34ea8d5b52b74eafa7a749a30d4d542d30ab6
> xtest: regression_1015: exclude when CFG_REE_FS not set

- host/xtest/CMakeLists.txt
- host/xtest/Makefile
- host/xtest/pkcs11_1000.c
- host/xtest/regression_4000.c
xtest: add CFG_CRYPTO_SE05X
--
The following cflag allows to disable  features not supported by
the SE05X hardware.
xtest: disable SE05X unsupported tests
--
The  SE050/1 secure elements do not support all the cryptographic
operations tested in the regression nor pkcs#11 tests.
Since the test framework wont handle a 'feature not supported' return
code from the secure world, this commit disables those tests that are
not supported by the hardware.
```
pkcs11:
RSA sign:
CKM_MD5_RSA_PKCS
RSA OAEP crypto:
RSA-OAEP/SHA224
RSA-OAEP/SHA224/label
RSA-OAEP/SHA256
RSA-OAEP/SHA256/label
RSA-OAEP/SHA384
RSA-OAEP/SHA384/label
RSA-OAEP/SHA512
RSA-OAEP/SHA512/label
regression:
RSA keypair generation:
RSA-256
RSA-384
RSA-640
RSA-768
RSA-896
```
> CFG_SE05X: consider the secure element hardware limitations when running the tests

- host/xtest/regression_1000.c
- ta/os_test/include/os_test.h
- ta/os_test/include/ta_os_test.h
- ta/os_test/pauth_a64.S
- ta/os_test/sub.mk
- ta/os_test/ta_arm_pauth.c
- ta/os_test/ta_entry.c
Added the PAuth test in os_test TA as suggested.
Test 1036 is added to test the ARM Security extension
feature PAuth (Pointer Authentication).
> [v2] ta: regression: Add test 1036 to test PAuth

- host/xtest/regression_6000.c
- ta/storage/storage.c
The TEE Internal Core API specification (v1.3.1) explicitly allows the
use of an empty object ID in TEE_RenamePersistentObject(). The text is:
newObjectID, newObjectIDLen: A buffer containing the new object
identifier. The identifier contains arbitrary bytes, including the
zero byte. The identifier length SHALL be less than or equal to
TEE_OBJECT_ID_MAX_LEN and can be zero.
(note the mention: "and can be zero").
Therefore, add a couple of test cases in regression_6008. Both
(non-NULL, 0) and (NULL, 0) are tested for the parameters
(newObjectID, newObjectIDLen).
Since it follows from the above that zero-sized object IDs are indeed
valid, similar test cases are added to regression_6001
(TEE_CreatePersistentObject()) and regression_6002
(TEE_OpenPersistentObject()).
Signed-off-by: Jerome …
> storage: add test cases with zero-sized object IDs

- host/xtest/regression_4000.c
Attribute TEE_ATTR_ECC_CURVE does not apply to SM2 keys. Do not set it
when generating or populating such key objects.
> regression 4006, 4014: do not set TEE_ATTR_ECC_CURVE for SM2

- host/xtest/regression_1000.c
- ta/os_test/attestation.c
- ta/os_test/include/os_test.h
- ta/os_test/include/ta_os_test.h
- ta/os_test/sub.mk
- ta/os_test/ta_entry.c
Add test cases for remote attestation: get public key, hash TEE
memory, get TA shdr digest, hash TA memory.
> xtest: add regression_1037 to test remote attestation

- host/xtest/regression_1000.c
Report the result of core dt_driver embedded tests in regression test 1001 next to other core self test.
Related to https://github.com/OP-TEE/optee_os/pull/5207.
> regression 1001: report dt_driver embedded test result

- host/xtest/regression_6000.c
The current code relies on compile-time defines (CFG_REE_FS and
CFG_RPMB_FS) to select the storage IDs that should be used when running
the secure storage tests (TEE_STORAGE_PRIVATE, TEE_STORAGE_PRIVATE_REE,
TEE_STORAGE_PRIVATE_RPMB). This doesn't work well when xtest is run with
a TEE core that was not built with the same defines. Although that is
not a generally supported thing, the storage differences can be handled
by adding a runtime check.
Some platforms don't have access to an RPMB while others may use only
RPMB (and disable the REE storage). By adding runtime detection, and
assuming other features are the same on all platforms, we can use the
same xtest binary in a common root FS image. One exmaple is the
Linaro LEDGE Reference Platform: the root FS [1] is shared while the …
> regression_6000.c: detect available storage IDs at runtime

- host/xtest/gp/include/xml_internal_api.h
- host/xtest/gp/patches/0014-Pass-upper-32-bits-of-TEE_PropSetHandle-in-value.b.patch
With MTE enabled 64-bit pointer usually use the upper 32 bits too while
the GP tests assumes that 32 bits are enough. Fix this by passing the
upper 32 bits in value.b
> GP: Pass upper 32 bits of TEE_PropSetHandle in value.b

- host/xtest/Makefile
In some rare occurrence and with a lot of parallel jobs, the following
compilation failure of xtest could happen:
GEN     out/xtest/regression_8100_ca_crt.h
python3 ../../scripts/file_to_c.py --inf ../../cert/ca.crt --out out/xtest/regression_8100_ca_crt.h --name regression_8100_ca_crt
Traceback (most recent call last):
File "../../scripts/file_to_c.py", line 48, in <module>
main()
File "../../scripts/file_to_c.py", line 24, in main
f = open(args.out, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'out/xtest/regression_8100_ca_crt.h'
make: *** [Makefile:226: out/xtest/regression_8100_ca_crt.h] Error 1
This is caused by the output directory `out/xtest/` not being created
when generating the following header files with the `embed-file` macro:
* regression_8100_ca_crt.h
* …
> xtest: create output dir before generating regression_8100 header files

- Makefile
When installing output files with the `install` Makefile target, the
output file ownership is preserved because the file copy to the
destination directory is done with `cp -a/--archive`.
When using the `install` Makefile target in a Yocto recipe, it triggers
the following Bitbake host contamination warning:
WARNING: optee-test-3.17.0.imx-r0 do_package_qa: QA Issue: optee-test: /lib/optee_armtz/b689f2a7-8adf-477a-9f99-32e90c0ad0a2.ta is owned by uid 1001, which is the same as the user running bitbake. This may be due to host contamination
optee-test: /lib/optee_armtz/5ce0c432-0ab0-40e5-a056-782ca0e6aba2.ta is owned by uid 1001, which is the same as the user running bitbake.  This may be due to host contamination
`cp` instead of `cp -a` solves the issue.
Fixes: 2a1ef2c76f ("Add install …
> Makefile: fix ownership contamination when installing output files

- host/xtest/regression_4000.c
When OP-TEE is built with MBedTLS as the core crypto library, X25519 is
not supported. Do not fail "xest regression_4007_x25519" in that case.
Note that a similar check is done in regression_4015 already.
Fixes: 00b3f2cbf4ad ("Add x25519 test cases")
> regression 4007_x25519: do not fail if X25519 is not supported

- Makefile
In host/supp_plugin/Makefile, CC is assigned the cross compiler set in
the Makefile only if the CC is not assigned any value previously. But
according to the GNU make implicit variables, CC will have a default
value of cc and hence the cross compiler set in the Makefile will not be
used while compiling the supp_plugin using makefiles.
"--no-builtin-variables" will cancel all variables used by implicit
rules.
Signed-off-by: Davidson K <davidson.kumaresan@arm.com>
> host: supp_plugin: fix cross compilation

- host/xtest/regression_1000.c
This fixes the following compilation issue:
external/optee_test/host/xtest/regression_1000.c:2817:56: error: unused parameter 'nonce' [-Werror,-Wunused-parameter]
static void check_measurement(ADBG_Case_t *c, uint8_t *nonce, size_t nonce_size,
^
external/optee_test/host/xtest/regression_1000.c:2817:70: error: unused parameter 'nonce_size' [-Werror,-Wunused-parameter]
static void check_measurement(ADBG_Case_t *c, uint8_t *nonce, size_t nonce_size,
^
Signed-off-by: Pierre Moos <pmoos@baylibre.com>
> xtest: fix compilation issue

- host/xtest/adbg/include/adbg.h
Removes the unused ADBG_REQUIRE* macros. It's not recommended to use those macros.
> xtest: remove ADBG_REQUIRE* macros

- Android.mk
- host/xtest/CMakeLists.txt
- host/xtest/Makefile
- host/xtest/ffa_spmc_1000.c
- host/xtest/include/uapi/linux/arm_ffa_user.h
- host/xtest/xtest_main.c
- host/xtest/xtest_test.h
Add support for testing the SPMC component inside OP-TEE. 
A new set of test have been added under regression_9000. This test some of the SPMC functionality. To be able to test this PR the [BUILD PR](https://github.com/OP-TEE/build/pull/584) is also needed. 
The SPs which are used on the Secure Wold to test the SPMC are currently under review on the Trusted Service gerrit server: https://review.trustedfirmware.org/c/TS/trusted-services/+/10159
Test can be run by using the following manifest file.
repo init -u https://github.com/jellesels-arm/manifest.git -m fvp-spmc-test.xml -b SPMC_TEST  &&  repo sync -j8 --no-clone-bundle
> FF-A: SPMC test

- host/xtest/pkcs11_1000.c
Adds tests to import, sign and verify Ed25519, Ed25519ctx and Ed25519ph.
The pull request comes with the following pull requests:
https://github.com/OP-TEE/optee_os/pull/5559
https://github.com/OP-TEE/optee_os/pull/5574
> PKCS#11 Ed25519 tests

- host/xtest/CMakeLists.txt
- host/xtest/Makefile
- host/xtest/gp/patches/0015-Enable-compatibility-with-TEE-Internal-Core-API-v1.1.patch
- host/xtest/regression_4000.c
- host/xtest/regression_4100.c
- host/xtest/regression_6000.c
- host/xtest/regression_8000.c
- host/xtest/regression_8100.c
- host/xtest/xtest_helpers.h
- host/xtest/xtest_uuid_helpers.h
- ta/ta_common.mk
While the TEE Internal Core API in OP-TEE OS is updated, enable compatibility with the last support version. This is done by compiling xtest with __OPTEE_CORE_API_COMPAT_1_1=1 and including <tee_api_compat.h> too. The TAs enable it with
CFG_TA_OPTEE_CORE_API_COMPAT_1_1==y in ta/ta_common.mk.
Backwards compatibility is enabled for the GP test suite TAs in the same way, using a new patch.
> Enable compatibility with TEE Internal Core API v1.1

- ta/Makefile
With the addition of regression_1039 tests, the compilation of subkey1 and subkey2 TAs is required in the Makefile for xtest to pass.
* regression_1039 Test subkey verification o regression_1039.1 Load TA with two levels of subkeys /usr/src/debug/optee-test/upstream.imx-r0/git/host/xtest/regression_1000.c:3206:xtest_teec_open_session(&session, &subkey1_ta_uuid, ((void *)0),&ret_orig) has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
regression_1039.1 FAILED
o regression_1039.2 Load TA with identity subkey
/usr/src/debug/optee-test/upstream.imx-r0/git/host/xtest/regression_1000.c:3213: xtest_teec_open_session(&session, &subkey2_ta_uuid, ((void *)0), &ret_orig) has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = …
> ta: makefile: add compilation of subkey TAs

- host/supp_plugin/CMakeLists.txt
Adds missing dependency of supp_plugin test on libteec header files that are brought in by libteec. The issue was reported by compiler with the below build error message:
/tmp/optee/optee_test/host/supp_plugin/test_supp_plugin.c:12:10: fatal error: tee_plugin_method.h: No such file or directory
12 | #include <tee_plugin_method.h>
|          ^~~~~~~~~~~~~~~~~~~~~
> host: supp_plugin: add missing dependency on teec

- host/xtest/regression_1000.c
- ta/supp_plugin/ta_entry.c
For the "Pass array to a plugin" sub-case make the passed buffer in/out since it's passed like that to in that TA with tee_invoke_supp_plugin().
> regression 1033: fix memref direction

- host/xtest/pkcs11_1000.c
Fixes the warning:
29659:  pkcs11_1000.c: In function ‘test_rsa_aes_wrap’:
29660:  pkcs11_1000.c:8249:51: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘size_t’ {aka ‘unsigned int’} [-Werror=format=]
29661:   8249 |    "Test RSA AES wrap/unwrap of %lu %s key with %lu RSA",
29662:        |                                                 ~~^
29663:        |                                                   |
29664:        |                                                   long unsigned int
29665:        |                                                 %u
29666:   8250 |    target_bits, (t->target_type == CKK_AES) ? "AES" : "RSA",
29667:   8251 |    t->key.modulus_len * 8);
29668:        |    ~~~~~~~~~~~~~~~~~~~~~~
29669:        | …
> pkcs11: fix regression in RSA AES key wrap tests

- host/xtest/pkcs11_1000.c
- host/xtest/xtest_uuid_helpers.c
- host/xtest/xtest_uuid_helpers.h
New PKCS11 test for TEE identity based authentication is added. 
C_InitToken with null pointer creates protected authentication path and then C_InitPin setup the ACL based user pin. 
Once initialization is completed, the current connection is closed and a new CKU_USER connection is opened. 
And then, login/logout test with ACL authentication is performed.
Signed-off-by: Matthew(Sukyoung) Chae <matthewc@axis.com>
> xtest: pkcs11: add PKCS11 ACL auth test

- host/xtest/pkcs11_1000.c
Commit b38e9e06fcbd ("xtest: pkcs11: add PKCS11 ACL auth test") added a new parameter to init_lib_and_find_token_slot() but omitted to update one call site. Fix that.
Fixes the following compile error:
pkcs11_1000.c: In function ‘xtest_pkcs11_test_1026’:
pkcs11_1000.c:8533:7: error: too few arguments to function ‘init_lib_and_find_token_slot’
8533 |  rv = init_lib_and_find_token_slot(&slot);
|       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> xtest: pkcs11: fix compile error with init_lib_and_find_token_slot()

- ta/os_test/os_test.c
RISC-V instruction size is 32-bits, 0x0 triggers an illegal instruction exception.
> riscv: ta: os_test: declare undefined instruction for RISC-V

- host/xtest/pkcs11_1000.c
64-bit xtest unsigned long is 8 bytes,while the
g_len is 4 bytes, crossing the bounds and causing
the contamination variable to g_decrypt
FAILED:
pkcs11_1000.c:3496: Expression "g_decrypt == CK_TRUE" (0 == 1) is false pkcs11_1014.1 FAILED
> xtest: pkcs11: fix 64-bit xtest_pkcs11_1014 failed

- host/xtest/pkcs11_1000.c
C_Finalize() is called from some places through close_lib() even before pkcs11 library is initialized. These needs to be replaced by return.
Signed-off-by: Matthew(Sukyoung) Chae <matthewc@axis.com>
> xtest: fix calling C_Finalize before lib is initialized

- host/xtest/regression_1000.c
- ta/os_test/os_test.c
Uses PTA stats during test to see when pager is enabled and operates with a small page pool. When so, some tests can be simplified or skiped unless what they are very slow to execute.
> regression 1006/1013: skip tests when pager is constrainted

- host/xtest/regression_6000.c
- ta/include/ta_storage.h
- ta/storage/storage.c
With the updated types for GP 1.3 TEE_ObjectInfo contains elements with the type size_t. If xtest is built for AArch64 while the storage TA is built for AArch32 the ABI will become incompatible. Fix this by adding struct ta_storage_obj_info with fixed width integers only and use that in the TA ABI used by xtest.
> Fix Storage TA ABI TEE_ObjectInfo

- host/xtest/pkcs11_1000.c
[Edited]
PKCS#11 PINs are UTF-8 character strings. The default SO PIN used in the
test suite contains a NUL, which causes issues with for example
pkcs11-tool which interprets the NUL byte as the end of the string, thus
making the slot impossible to use from the command line.
Therefore, and for better compatibility with command-line tools after
xtest has been run, use simpler (ASCII) values for both the SO and user
PINs.
> pkcs11: remove NUL byte from SO PIN and use ASCII characters

- host/xtest/regression_6000.c
Since OP-TEE commit cda03b63cf30 ("Enable SHA-3 support by default") [1] regression_6016 fails when OP-TEE OS is compiled for QEMUv8 with "make CFG_ULIBS_SHARED=y CFG_WITH_PAGER=y":
* regression_6016 Storage concurency o regression_6016.1 Storage id: 00000001 threads: 4, loops: 8 regression_6000.c:1784: xtest_teec_open_session(&arg[m].session, &storage_ta_uuid, ((void *)0), &orig) has an unexpected value: 0xffff000c = TEEC_ERROR_OUT_OF_MEMORY, expected 0x0 = TEEC_SUCCESS
Use 3 threads instead of 4 to reduce the memory footprint.
Link: [1] https://github.com/OP-TEE/optee_os/commit/cda03b63cf304472adce7688a07168f4c66af5c7
> xtest: regression_6016: use 3 threads instead of 4

- host/xtest/pkcs11_1000.c
When ACL test is running with login type is group, it fails to run C_Initialize. Fix this by sending the correct group id.
> xtest: pkcs11: fix the ACL authentication fail

- host/xtest/regression_1000.c
Reviewed-by: liushiwei <liushiwei@eswincomputing.com>
> xtest: regression_1037: Close attestation session

- Android.mk
- host/xtest/CMakeLists.txt
- host/xtest/Makefile
- host/xtest/clear_storage.c
- host/xtest/clear_storage.h
- host/xtest/xtest_main.c
- ta/include/ta_storage.h
- ta/storage/include/storage.h
- ta/storage/storage.c
- ta/storage/ta_entry.c
One small fix plus a new option: `xtest --clear-storage`.
> Storage cleanup

- ta/storage/storage.c
Adds __maybe_unused attribute to local variable hold the TA UUID to fix build warning reported by GCC with the below trace:
../storage/storage.c: In function ‘clear_storage’: ../storage/storage.c:674:18: error: unused variable ‘uuid’ [-Werror=unused-variable]
674 |         TEE_UUID uuid = TA_UUID;
|                  ^~~~
Fixes: aa43c9084e21 ("xtest: add --clear-storage option")
> ta: storage: maybe usued TA UUID in clear_storage()

- host/xtest/aes_perf.c
- host/xtest/hash_perf.c
- host/xtest/sdp_basic.c
- host/xtest/stats.c
Fixes the xtest program name printed in applets usage and error trace messages. Stats applet assumes it is named xtest instead of using caller argv[0]. Other applets simply print the applet option name instead of xtest tool name followed by applet option name.
> xtest: fix xtest tool name in usage trace messages

- host/xtest/ffa_spmc_1000.c
`commit 5489e94f0566 ("core: ffa: add boot info structs and defines")` in optee_os causes the compiler error below in `ffa_spmc_1000.c`.
```
In file included from ffa_spmc_1000.c:6:
ffa.h:196:41: error: implicit declaration of function ‘U’ [-Werror=implicit-function-declaration]
196 | #define FFA_BOOT_INFO_NAME_LEN          U(16)
|                                         ^
ffa.h:319:19: note: in expansion of macro ‘FFA_BOOT_INFO_NAME_LEN’
319 |         char name[FFA_BOOT_INFO_NAME_LEN];
|                   ^~~~~~~~~~~~~~~~~~~~~~
ffa.h:319:14: error: variably modified ‘name’ at file scope
319 |         char name[FFA_BOOT_INFO_NAME_LEN];
|              ^~~~
```
`ffa.h` uses the `U` macro which is only part of OP-TEE's libc and not a standard macro. This causes a compiler error when …
> xtest: remove ffa.h from SPMC test to resolve compiler error

- host/xtest/regression_4000.c
Explicit uses the stack to refer to attribute TEE_ATTR_RSA_OAEP_MGF_HASH passed to the crypt TA in tests regression 4006.37 and 4006.38 as the current implementation makes to TA to see an uninitialized buffer reference.
Fixes: https://github.com/OP-TEE/optee_os/issues/6143
> regression_4006: fix fuzzing shared memory content

- host/xtest/regression_1000.c
Symptom:
Run xtest test cannot finish all test cases due to there is Segmentation faultthat stop at regression 1034 test case.
Snapshot log as below:
* regression_1034 Test loading a large TA /usr/src/debug/optee-test/3.20.0-r0/host/xtest/
regression_1000.c:2524:res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS Segmentation fault (core dumped)
Root cause:
In regression 1034 test function, when opening session for large TA got failed because response that large TA not found. However, this function still call TEEC_CloseSession then cause Segmentation fault. According the log, the ADBG_EXPECT_TEEC_SUCCESS(c, res) function response with TEEC_ERROR_ITEM_NOT_FOUND this error message.
Solution:
Add additional check if response with …
> regression_1034: fix Segmentation fault when large TA not found

- host/xtest/regression_1000.c
Hack to work around musl compile error:
In file included from optee-test/3.17.0-r0/recipe-sysroot/usr/include/sys/stat.h:23,
from optee-test/3.17.0-r0/git/host/xtest/regression_1000.c:25:
optee-test/3.17.0-r0/recipe-sysroot/usr/include/bits/stat.h:17:26: error: expected identifier or '(' before '[' token
17 |         unsigned __unused[2];
|                          ^
stat.h is not needed, since it is not being used in this file.  So removing it.
> xtest: regression_1000: remove unneeded stat.h include

- host/xtest/regression_1000.c
Adds regression case 1040 to test panic in concurrent open/invoke/close session.
> xtest: regression: add case 1040

- host/xtest/stats.c
Command format: xtest --stats --time
Tested-by: Weizhao Jiang <weizhaoj@amazon.com>
> xtest: add command to get system time

- ta/crypt/mbedtls_taf.c
The mbedtls_pk_parse_key() has two new paramters with the new 3.x API in. Fix the call of mbedtls_pk_parse_key(). The X.509 self test is removed so remove the call to that test in the TA.
Acked-by: Jerome Forissier <jerome.forissier@linaro.org>
> ta/crypt: update to mbedTLS 3.4.0 API

- host/xtest/gp/patches/0016-TEE_Crypto_API.xml.patch
Some tests for TEE_AllocateOperation() are invalid because they assume the function should reject non-zero maxKeySize values but the specification was clarified to explicitly allow them. Add a patch file to disable those tests.
> gp: disable tests gp_50360, gp_50398, gp_50400, gp_50402, gp_50404 and gp_50406

- ta/os_test/os_test.c
…time comparaison
In the regression_1006 test, the wrapped TA time is compared to the system time. The time delay for this test is one second. The system time is fetched at the very begining of the test function.
For this test to pass, it is assumed that the system time fetched is at least one second. That might not be the case in a system where the test is started right after a deep sleep state where the system counter gets reset.
To solve this issue, fetch the system counter after the one second delay.
> ta: os_test: fetch system time after the one second delay for proper comparaison

- ta/os_test/include/tb_asserts.h
- ta/os_test/include/tb_macros.h
Removes macros TB_PRINT_BIGINT() and TB_ASSERT_HEX_PRINT_VALUE() that are never used. These macros depend in TEE_STRING_MODE_HEX_UC which has been removed from optee_os. It was removed from OP-TEE because it was related to libmpa removed from OP-TEE OS since release tag 3.9.0, by commit 7fb525f1f8a6 ("Remove libmpa in favor of libmbedtls").
Link: https://github.com/OP-TEE/optee_os/pull/6451
> ta: os_test: remove deprecated macro related to libmpa

- host/xtest/stats.c
The command 'xtest --stats --time' is not documented in the usage
description
> Update help of xtest --stats

- host/xtest/pkcs11_1000.c
`optee_test` does not compile if openssl is not found (or purposely excluded). This PR addresses this issue by skipping two tests which depends on openssl. While at it, also do a small clean-up and remove one trailing whitespace.
More details in the individual commit descriptions.
> Fix build if no openssl

- ta/os_test/include/tb_asserts.h
- ta/os_test/os_test.c
- ta/rpc_test/ta_rpc.c
- ta/sdp_basic/ta_sdp_basic.c
- ta/storage_benchmark/benchmark.c
This is a tree wide fix to remove all the trailing newlines in the `*MSG()` macros.
> No newline in *MSG() macros

- host/xtest/pkcs11_1000.c
Fix false positive error case in test pkcs11_1004 and pkcs11_1007.
In the pkcs11_1004 test, the client creates as many PKCS#11 objects as possible until the system fails on memory allocation error. In the pkcs11_1007 test, the client prepares as many cipher sessions as possible until the system fails on memory allocation error. Both test implementations consider only CKR_DEVICE_MEMORY return code as the condition for expected resource exhaustion while they should also consider the host resource exhaustion return code CKR_HOST_MEMORY.
Fixes: 2d6dc9312935 ("xtest: pkcs11: add symmetric cipher tests")
> xtest: pkcs11: fix false positive error report on CKR_HOST_MEMORY

- host/xtest/regression_6000.c
- ta/storage/storage.c
Depends on the fix in https://github.com/OP-TEE/optee_os/pull/6505
> Restric usage

- ta/os_test/include/tb_macros.h
- ta/os_test/os_test.c
- ta/rpc_test/ta_rpc.c
- ta/sdp_basic/ta_sdp_basic.c
- ta/storage_benchmark/benchmark.c
This is a follow up of cleanup changes initiated in https://github.com/OP-TEE/optee_test/pull/708 and https://github.com/OP-TEE/optee_test/pull/709 to have TA trace messages implementation more consistent with OP-TEE coding style and trace resources.
> ta: cleanup trace messages in test TAs

- host/xtest/stats.c
This P-R depends on https://github.com/OP-TEE/optee_os/pull/6521.
> xtest: stats: used exported PTA API + print clock/regulator trees

- host/xtest/pkcs11_1000.c
OP-TEE's PKCS#11 TA TEE<->REE interface treats `CK_ULONG`'s as 32 bit.
In 64 bit machines this creates a problem for `CK_ULONG` values that are architecture dependent.
One of those defines is `CK_UNAVAILABLE_INFORMATION`.
This adds test case to make sure that when OP-TEE's PKCS#11 TA should give `CK_UNAVAILABLE_INFORMATION` it actually does that.
Depends on:
- https://github.com/OP-TEE/optee_client/pull/367
> xtest: pkcs11: Add check that CK_TOKEN_INFO outputs correct CK_ULONG's

- .github/workflows/ci.yml
Remove unneeded files from the root filesystem to avoid a "No space left on device" error. A similar trick was committed to optee_os for the same reason [1].
Link: https://github.com/OP-TEE/optee_os/commit/fa1950059f4128a9b58558d4970c153595463ff3 [1]
> ci: avoid "No space left on device" error

- host/xtest/pkcs11_1000.c
This P-R supersedes https://github.com/OP-TEE/optee_test/pull/720.
These test depends on https://github.com/OP-TEE/optee_os/pull/6683 and https://github.com/OP-TEE/optee_client/pull/375.
> xtest: pkcs11_1000.c: Add tests for AES-GCM (take 2)

- ta/os_test/ta_entry.c
The specification seems to indicate (see https://github.com/OP-TEE/optee_test/issues/731)
that the cancellation mask is reset at the start of every entry point.
As a result, the TEE_UnmakCancellation() should not be called at the end of
TA_OpenSessionEntryPoint(), but at the start of TA_InvokeCommandEntryPoint().
Also, note that this patch should not break the current test.
Still, there is a test which could be written to test that unmasking cancellations
really does not affect subsequent entry points. There is no such test for now,
and if one were designed, then the current implementation would report a failure to this test,
until the implementation is fixed with respect to the Global Platform specification.
If you need such a test, I could consider writing one.
> cancellation: Unmask inside of invoke command

- host/xtest/gp/include/xml_common_api.h
- host/xtest/gp/include/xml_crypto_api.h
- host/xtest/gp/include/xml_datastorage_api.h
- host/xtest/gp/include/xml_internal_api.h
- host/xtest/gp/include/xml_timearithm_api.h
- host/xtest/regression_1000.c
Depends on (and is required due to) https://github.com/OP-TEE/optee_client/pull/349.
> Updates for the new 'imp' field in TEEC_Session and TEEC_Context

- host/xtest/asym_perf.c
- ta/crypto_perf/include/ta_crypto_perf.h
- ta/crypto_perf/ta_crypto_perf.c
add perf test for SM2 algorithm
> xtest: add SM2 perf test

- host/xtest/regression_6000.c
- ta/storage/storage.c
[Desc]:
1. check_storage_available should check fs_unlink's return value.
2. ta_storage_cmd_unlink should't always return TEE_SUCCESS.
> [BugFix]: Add ruturn value check for fs_unlink and ta_storage_cmd_unlink

- .github/workflows/ci.yml
The newer version of Buildroot recently selected in the OP-TEE manifest [1] does not allow building as root by default (apparently this is not a Buildroot policy but rather defined in some packages included in Buildroot). While this makes sense in general, we could not care less in a CI container. Therefore set the appropriate environment variable to bypass this check. We could as well change the Docker image to build as a non-root user but let's just pick the easiest way for now.
Link: https://github.com/OP-TEE/manifest/pull/281 [1]
> ci: set FORCE_UNSAFE_CONFIGURE=1

- host/xtest/regression_4000.c
- ta/crypt/cryp_taf.c
Depends on https://github.com/OP-TEE/optee_os/pull/6802
> xtest regression case 4017

- LICENSE-BSD
- LICENSE-GPL
- LICENSE.md
Resolves #748. The BSD license text's year and copyright holder are copied from https://github.com/OP-TEE/optee_os/blob/master/LICENSE
> license: Add text of GPL-2.0 and BSD-2 licenses to repository

- Android.mk
Commit bcd55831e1f7 ("xtest: add asymmetric cipher perf test") introduces a build error for xtest on AOSP 14:
```
external/optee_test/host/xtest/asym_perf.c:125:71: error: unused parameter 'main_algo' [-Werror,-Wunused-parameter] static void usage(const char *progname, uint32_t width_bits, uint32_t main_algo,
^
external/optee_test/host/xtest/asym_perf.c:126:14: error: unused parameter 'mode' [-Werror,-Wunused-parameter]
uint32_t mode, uint32_t salt_len, uint32_t size,
^
external/optee_test/host/xtest/asym_perf.c:127:14: error: unused parameter 'crypto_algo' [-Werror,-Wunused-parameter]
uint32_t crypto_algo, int warmup, uint32_t l, uint32_t n)
^
external/optee_test/host/xtest/asym_perf.c:668:76: error: unused parameter 'size' [-Werror,-Wunused-parameter] static int …
```
> Android.mk: add -Wno-unused-parameter CFLAGS for xtest

- LICENSE-BSD
The copyright notice is part of the license text (see https://opensource.org/license/bsd-2-clause). I mistakenly removed this when applying review feedback for #749 - sorry about that. This adds the line back.
> license: Add copyright notice line to BSD license text

- Android.mk
- host/xtest/CMakeLists.txt
- host/xtest/Makefile
- host/xtest/include/uapi/linux/dma-heap.h
Copy the needed dma-heap.h from Linux kernel v6.9. This is a stable ABI so it doesn't have to be synced with each new kernel.
dma-heap.h can be removed when the cross toolchains provide the file.
> xtest: copy dma-heap.h from Linux kernel v6.9

- host/xtest/pkcs11_1000.c
Fix test_find_objects() so that C_FindObjectsFinal() is properly called even if we don't find the expected number of objects.
Fixes: afe2b54fb68b ("xtest: pkcs11: add find object tests")
> xtest: pkcs11: fix test_find_objects() when wrong count

- host/xtest/pkcs11_1000.c
Close opened session after secure service memory is exhausted before testing closure on invalid session. This change attempts to fix a non systematic issue found as described in [1].
A test case is slightly changed: where a likely invalid session ID (valid ID + 1024) was tried to be closed, this change now tries to close a session that has been already closed.
Link: https://github.com/OP-TEE/optee_os/issues/6952 [1]
> pkcs11_1007: close session before trying new ones

- host/xtest/CMakeLists.txt
We have been using an outdated version of xalan, which is what is installed using apt in Ubuntu. If you run Fedora, you will receive the latest version. The executable name has changed from "xalan" to "Xalan" and the supported command line arguments are also different. Therefore supporting different versions of xalan across distros can be challenging.
One alternative is xsltproc. It looks like it works on both Ubuntu and Fedora, so let's swap out xalan for xsltproc.
Tested-by: Joakim Bech <joakim.bech@linaro.org> (Fedora 41)
Tested-by: Joakim Bech <joakim.bech@linaro.org> (Ubuntu 22.04)
> gp: change from xalan to xsltproc

- host/xtest/pkcs11_1000.c
Skip CKM_RSA_PKCS test in pkcs11_1021 is the mechanism is not supported. This is likely to append when OP-TEE core is built with CFG_CRYPTO_RSASSA_NA1 disabled as when built with MbedTLS as core crypto library.
> xtest: pkcs11_1021: skip CKM_RSA_PKCS test is not supported

- host/xtest/pkcs11_1000.c
- host/xtest/regression_4000.c
Following the issue reported and fixed by https://github.com/OP-TEE/optee_os/pull/7162, I add some tests to request asymmetric signature providing a too small signature output buffer.
Tested with both CFG_CRYPTOLIB_NAME={tomcrypt|mbedtls}`.
Changes in **regression_4006** covers the RSA/ECC cases, already handled in OP-TEE even before tag 4.4.0.
Changes in **regresison_4016** and **pkcs11_1025** covers the ED25519 cases and require https://github.com/OP-TEE/optee_os/pull/7162 (recently merged) to succeed.
> xtest: asymm signature with a too small buffer (regression 4006/4016 + pkcs11 1025)

- .github/workflows/ci.yml
Update the CI container to jforissier/optee_os_ci:qemu_check [1] which is the latest one, usable for both 32-bit and 64-bit ARM, and which is used by the optee_os CI [2]. This one should be able to build QEMU 9.2.0 without any issue contrary to the current one which causes:
*** Ouch! ***
found no usable tomli, please install it
Link: https://github.com/jforissier/docker_optee_os_ci/tree/qemu_check [1]
Link: https://github.com/OP-TEE/optee_os/blob/4.4.0/.github/workflows/ci.yml#L319 [2]
> ci: update container

- host/xtest/ftpm_ta.h
- host/xtest/regression_1000.c
Add regression case 1041 to test if the system has a fTPM TA and if so check that it has been probed.
> regression: add case 1041 for fTPM

- Android.mk
- host/xtest/CMakeLists.txt
- host/xtest/Makefile
- host/xtest/install_ta.c
- host/xtest/xtest_main.c
Makes xtest tool more flexible regarding OP-TEE configuration of `CFG_SECSTOR_TA_MGMT_PTA`.
Embed TA install interface in xtest even if devkit configuration says the secure storage TA management PTA service is not available. If the service is not found (secstor TA management PTA) print an explicit error message instead.
This change does not change xtest regression suite behavior and will still fails if one uses `--install-ta` option when the effective embedded TEE does not provide this service. This change adds an explicit error message when so.
> xtest: remove CFG_SECSTOR_TA_MGMT_PTA dependency

- host/xtest/regression_1000.c
It does take some time for the kernel to probe the fTPM device, and therefore if regression_1041 is run immediately after boot it may fail. Add a 5 second timeout to make the test reliable.
> regression_1041: give 5 seconds for /dev/tpm0 to appear

- host/xtest/regression_4000.c
Split regression_4006 test cases into specific test cases for each of RSA, DSA, ECDSA and SM2. This eases testing only a target algo family without needing to run all the cases series, especially useful when testing all algo flavors (max test level with option "-l 15").
By the way, fix the test cases description that mention "Asymm Cipher" while both ciphering and authentication operation are tested.
> regression_4000: split test cases per algo family

- host/xtest/regression_4000_data.h
Replace deprecated TEE_ALG_ECDH_P192, TEE_ALG_ECDH_P224, TEE_ALG_ECDH_P256, TEE_ALG_ECDH_P384 and TEE_ALG_ECDH_P521 with TEE_ALG_ECDH_DERIVE_SHARED_SECRET that defines the ECDH key derivation algorithm with any EC key size.
> regression_4009: update deprecated TEE_ALG_ECDH_P*

- host/xtest/regression_4000.c
Make xtest tool more flexible regarding OP-TEE configuration of CFG_CRYPTO_RSASSA_NA1. If algorithm TEE_ALG_RSASSA_PKCS1_V1_5 is not supported then it means either OP-TEE OS libraries or OP-TEE core were built with CFG_CRYPTO_RSASSA_NA1=n in which case simply don not test this algorithm.
> regression_4006: remove CFG_CRYPTO_RSASSA_NA1 dependency

- host/xtest/regression_1000.c
The timeout for /dev/tpm0 to appear was previously 5 seconds, but that's not always enough so increase it to 20 seconds to have a larger margin.
> regression_1041: increase ftpm timeout to 20 seconds

- ta/os_test/os_test.c
In the test for wrapped TA time in test_time() we check that the time has wrapped and that not too much time has passed. The limit for this is currently 2 seconds of which 1 second is passed in TEE_Wait(). This is currently not enough time with the recent introduction of fTPM being probed in parallel with the test. So in order to avoid occasional false negatives increase the limit to 60 seconds.
Fixes: a2c1ce3a8c31 ("ta: os_test: fix TA time wrap test")
> ta: os_test: fix TA time wrap test

- host/xtest/regression_1000.c
- host/xtest/regression_6000.c
- ta/concurrent/include/ta_concurrent.h
'Concurent' and 'concurency' are typo. They should be 'Concurrent' and 'concurrency' instead.
> xtest: Fix typo from 'Concurent' to 'Concurrent'

- host/xtest/stats.c
A new field is added to struct pta_stats_alloc, free2_sum, the sum of size^2 of each free chunk. This can be used to calculate a fragmentation metric for the heap [1]. Some examples with xtest --stats --alloc:
When booted:
Pool:                Heap
Bytes allocated:                       21376
Fragmentation:			       3 %
Max bytes allocated:                   21488
Size of pool:                          202608
At some point during xtest:
Pool:                Heap
Bytes allocated:                       31616
Fragmentation:			       54 %
Max bytes allocated:                   101312
Size of pool:                          202608
When xtest has completed:
Pool:                Heap
Bytes allocated:                       25824
Fragmentation:			       33 %
Max bytes allocated: …
> xtest: stats: report heap fragmentation metric

- ta/crypto_perf/ta_crypto_perf.c
Fix: #785
Clearing crypto_op after freeing it,
allowing the TA to be called again without crashing.
Signed-off-by: Wenxing Hou <houwenxing@xiaomi.com>
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
> ta: crypto_perf: clear crypto_op after free

- CMakeLists.txt
CMake 4.0 was released [1] which dropped compatibility with versions older than 3.5 and causes cmake_minimum_required(3.4) to fail. Bump the minimum required version to 3.5, which was released 9 years ago.
[1] https://www.kitware.com/cmake-4-0-0-available-for-download/
With v4.0.0 the following build error is observed:
|  CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
|  Compatibility with CMake < 3.5 has been removed from CMake.
|
|  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
|  to tell CMake that the project requires at least <min> but has been updated
|  to work with policies introduced by <max> or earlier.
|
|  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
> cmake: raise minimum required to 3.5

- host/xtest/regression_1000.c
Add test entry for transfer list in xtest 1001.
> xtest: add test entry for transfer list

- host/xtest/regression_4000.c
- host/xtest/regression_4000_data.h
GCC 15 now warns when character arrays are being initialized by strings
and terminating NUL character doesn't fit. GCC 15.1 also allows marking
such arrays with nonstring attribute to suppress the warning. W/o such
attribute, the warning becomes error due to the global -Werror. Add the
attribute accordingly.
> Suppress new gcc-15 -Wunterminated-string-initialization

- Android.mk
- CMakeLists.txt
- host/xtest/Makefile
Fix the following build error (QEMU build in this instance):
$ export GP=TEE_Initial_Configuration-Test_Suite_v2_0_0_2-2017_06_09.7z $ make -j$(nproc) GDBSERVER=y \
GP_PACKAGE=/home/builder/optee/$GP
[...]
/home/builder/optee/out-br/build/optee_test_ext-1.0/host/xtest/gp_10000.c: In function 'gp_test_teec_10086': /home/builder/optee/out-br/build/optee_test_ext-1.0/host/xtest/gp/include/xml_client_api.h:162:18: error: allocation of insufficient size '0' for type 'uint8_t' {aka 'unsigned char'} with size '1' [-Werror=alloc-size]
162 |         temp_mem = malloc(size)
|                  ^
/home/builder/optee/out-br/build/optee_test_ext-1.0/host/xtest/gp_10000.c:1757:5: note: in expansion of macro 'AllocateTempMemory'
1757 |     AllocateTempMemory(TEMP_MEM01, ZERO);
|     ^~~~~~~~~~~~~~~~~~ …
> xtest: fix build with GP_PACKAGE and GCC 14

- host/xtest/regression_4000.c
Change default value of `middle_count` in regression test 4017 when test level is below 12. Instead of 0, use 2. This allows to pass few tests feeding data byte per byte without increasing the test duration as when test level is 12 or above.
> regression_4017: Test few one-by-one byte cases in level 0

- host/xtest/regression_1000.c
With musl, the compilation of optee-test would fail:
|   GEN     optee-test/4.6.0/optee-test-4.6.0/xtest/regression_8100_ca_crt.h
| python3 ../../scripts/file_to_c.py --inf ../../cert/ca.crt --out optee-test/4.6.0/optee-test-4.6.0/xtest/regression_8100_ca_crt.h --name regression_8100_ca_crt
| In file included from optee-test/4.6.0/recipe-sysroot/usr/include/sys/stat.h:30,
|                  from optee-test/host/xtest/regression_1000.c:24:
| optee-test/4.6.0/recipe-sysroot/usr/include/bits/stat.h:17:26: error: expected identifier or '(' before '[' token
|    17 |         unsigned __unused[2];
|       |                          ^
The defintion of OP-TEE macro __unused conflicts with the musl implementation and its use of variables named __unused.
Re-ordering and including <sys/stat.h> …
> regression_1000: Re-order the include of <sys/stat.h> header

- .github/workflows/stale_issue.yml
Update actions/stale@v4.1.0 to the latest version (v10.0.0). One difference is that issues and PRs are closed by the bot as "not_planned" rather than "completed", which is the main reason for updating.
> github: update stale workflow to v10.0.0
